// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class Addresses
{
    public int AddressID { get; set; }

    public string? FullAddress { get; set; }

    public string? Street { get; set; }

    public string? City { get; set; }

    public string? State { get; set; }

    public string? Additionaladdress { get; set; }

    public string? PostalCode { get; set; }

    public int? CountryID { get; set; }

    public string? Phone { get; set; }

    public string? OtherPhone { get; set; }

    public string? Email { get; set; }

    public decimal? Latitude { get; set; }

    public decimal? Longitude { get; set; }

    public string? LIP { get; set; }

    public string? LMAC { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }

    public string? FirstName { get; set; }

    public string? LastName { get; set; }

    public virtual ICollection<CompanyBranchAddresses> CompanyBranchAddresses { get; set; } = new List<CompanyBranchAddresses>();

    public virtual ICollection<CompanyWarehouseAddresses> CompanyWarehouseAddresses { get; set; } = new List<CompanyWarehouseAddresses>();

    public virtual Country? Country { get; set; }

    public virtual Employees? CreatedByNavigation { get; set; }

    public virtual Employees? CreatedByNavigation { get; set; }
    public virtual ICollection<CustomerAddresses> CustomerAddresses { get; set; } = new List<CustomerAddresses>();

    public virtual Employees? DeletedByNavigation { get; set; }

    public virtual ICollection<OtherContacts> OtherContacts { get; set; } = new List<OtherContacts>();

    public virtual Employees? UpdatedByNavigation { get; set; }
}