// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class Attendance
{
    public int AttendanceID { get; set; }

    public int? EmployeeID { get; set; }

    public DateOnly AttendanceDate { get; set; }

    public int? StatusID { get; set; }

    public int? ShiftID { get; set; }

    public DateTime? CheckInTime { get; set; }

    public DateTime? CheckOutTime { get; set; }

    public string Remarks { get; set; }

    public string LIP { get; set; }

    public string LMAC { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }

    public decimal? RegularHour { get; set; }

    public decimal? OvertimeHour { get; set; }

    public decimal? LateHour { get; set; }

    public decimal? EarlyHour { get; set; }

    public decimal? WorkingHour { get; set; }

    public virtual ICollection<AttendanceLog> AttendanceLog { get; set; } = new List<AttendanceLog>();

    public virtual Employees CreatedByNavigation { get; set; }

    public virtual Employees DeletedByNavigation { get; set; }

    public virtual Employees Employee { get; set; }

    public virtual Shifts Shift { get; set; }

    public virtual Statuses Status { get; set; }

    public virtual Employees UpdatedByNavigation { get; set; }
}