// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class BankAccountInfo
{
    public int BankAccountInfoID { get; set; }

    public int? BankID { get; set; }

    public int? BankBranchID { get; set; }

    public string? AccountName { get; set; }

    public string? AccountNumber { get; set; }

    public int? HeadID { get; set; }

    public string? LIP { get; set; }

    public string? LMAC { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }

    public virtual Banks? Bank { get; set; }

    public virtual BankBranches? BankBranch { get; set; }

    public virtual Employees? CreatedByNavigation { get; set; }

    public virtual Employees? DeletedByNavigation { get; set; }

    public virtual Heads? Head { get; set; }

    public virtual ICollection<PaymentChequeInfo> PaymentChequeInfo { get; set; } = new List<PaymentChequeInfo>();

    public virtual Employees? UpdatedByNavigation { get; set; }
}