// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class Banks
{
    public int BankID { get; set; }

    public string BankName { get; set; }

    public string SwiftCode { get; set; }

    public string Comment { get; set; }

    public string LIP { get; set; }

    public string LMAC { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }

    public virtual ICollection<BankAccountInfo> BankAccountInfo { get; set; } = new List<BankAccountInfo>();

    public virtual ICollection<BankBranches> BankBranches { get; set; } = new List<BankBranches>();

    public virtual ICollection<ChequeDetails> ChequeDetails { get; set; } = new List<ChequeDetails>();

    public virtual Employees CreatedByNavigation { get; set; }

    public virtual Employees DeletedByNavigation { get; set; }

    public virtual ICollection<PaymentTransactions> PaymentTransactions { get; set; } = new List<PaymentTransactions>();

    public virtual Employees UpdatedByNavigation { get; set; }
}