// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class Challans
{
    public int ChallanID { get; set; }

    public string ChallanNumber { get; set; }

    public int? InvoiceID { get; set; }

    public DateTime? ChallanDate { get; set; }

    public DateTime? ExpectedDeliveryDate { get; set; }

    public DateTime? ActualDeliveryDate { get; set; }

    public int? StatusID { get; set; }

    public int? DeliveryMethodID { get; set; }

    public string TrackingNumber { get; set; }

    public int? DeliveryAddressID { get; set; }

    public string Note { get; set; }

    public decimal? DeliveryCost { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }

    public int? SalesOrdersVersionID { get; set; }

    public virtual ICollection<ChallanItems> ChallanItems { get; set; } = new List<ChallanItems>();

    public virtual Employees CreatedByNavigation { get; set; }

    public virtual Employees DeletedByNavigation { get; set; }

    public virtual Addresses DeliveryAddress { get; set; }

    public virtual DeliveryMethods DeliveryMethod { get; set; }

    public virtual Invoices Invoice { get; set; }

    public virtual SalesOrdersVersions SalesOrdersVersion { get; set; }

    public virtual Statuses Status { get; set; }

    public virtual Employees UpdatedByNavigation { get; set; }
}