// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class CreditNote
{
    public int CreditNoteID { get; set; }

    public string? CreditNoteNo { get; set; }

    public int? InvoiceID { get; set; }

    public DateOnly? CreditDate { get; set; }

    public string? Reason { get; set; }

    public decimal? VatPercentage { get; set; }

    public decimal? VatAmount { get; set; }

    public decimal? SubTotal { get; set; }

    public decimal? GrandTotal { get; set; }

    public string? LIP { get; set; }

    public string? LMAC { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }

    public virtual Employees? CreatedByNavigation { get; set; }

    public virtual ICollection<CreditNoteItems> CreditNoteItems { get; set; } = new List<CreditNoteItems>();

    public virtual Employees? DeletedByNavigation { get; set; }

    public virtual Invoices? Invoice { get; set; }

    public virtual Employees? UpdatedByNavigation { get; set; }
}