// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class CustomerAddresses
{
    public int CustomerAddressID { get; set; }

    public int? AddressTypeID { get; set; }

    public int? AddressID { get; set; }

    public string LIP { get; set; }

    public string LMAC { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }

    public int? CustomerID { get; set; }

    public virtual Addresses Address { get; set; }

    public virtual AddressTypes AddressType { get; set; }

    public virtual Employees CreatedByNavigation { get; set; }

    public virtual Customers Customer { get; set; }

    public virtual Employees DeletedByNavigation { get; set; }

    public virtual Employees UpdatedByNavigation { get; set; }
}