// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class Departments
{
    public int DepartmentID { get; set; }

    public string DepartmentName { get; set; } = null!;

    public string? LIP { get; set; }

    public string? LMAC { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }

    public int? OrganizationID { get; set; }

    public int? DepartmentHeadEmpID { get; set; }

    public virtual Employees? CreatedByNavigation { get; set; }

    public virtual Employees? DeletedByNavigation { get; set; }

    public virtual Employees? DepartmentHeadEmp { get; set; }

    public virtual ICollection<EmployeeFinalShifts> EmployeeFinalShifts { get; set; } = new List<EmployeeFinalShifts>();

    public virtual ICollection<EmployeeOfficeInfo> EmployeeOfficeInfo { get; set; } = new List<EmployeeOfficeInfo>();

    public virtual ICollection<EmployeeTransfer> EmployeeTransferFromDepartment { get; set; } = new List<EmployeeTransfer>();

    public virtual ICollection<EmployeeTransferHistory> EmployeeTransferHistoryFromDepartment { get; set; } = new List<EmployeeTransferHistory>();

    public virtual ICollection<EmployeeTransferHistory> EmployeeTransferHistoryToDepartment { get; set; } = new List<EmployeeTransferHistory>();

    public virtual ICollection<EmployeeTransfer> EmployeeTransferToDepartment { get; set; } = new List<EmployeeTransfer>();

    public virtual Organization? Organization { get; set; }

    public virtual ICollection<RosterInHolyDays> RosterInHolyDays { get; set; } = new List<RosterInHolyDays>();

    public virtual ICollection<RosterInOfficeDays> RosterInOfficeDays { get; set; } = new List<RosterInOfficeDays>();

    public virtual ICollection<SpiralPatternAssignList> SpiralPatternAssignList { get; set; } = new List<SpiralPatternAssignList>();

    public virtual Employees? UpdatedByNavigation { get; set; }
}