// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace GCTL.Data.Models;

public partial class Departments
{
    public int DepartmentID { get; set; }

    public string DepartmentName { get; set; }

    public string LIP { get; set; }

    public string LMAC { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }

    public int? OrganizationID { get; set; }

    public int? DepartmentHeadEmpID { get; set; }

    public virtual Employees CreatedByNavigation { get; set; }

    public virtual ICollection<DefaultShifts> DefaultShifts { get; set; } = new List<DefaultShifts>();

    public virtual Employees DeletedByNavigation { get; set; }

    public virtual ICollection<EmployeeOfficeInfo> EmployeeOfficeInfo { get; set; } = new List<EmployeeOfficeInfo>();

    public virtual Organization Organization { get; set; }

    public virtual ICollection<RosterInHolyDays> RosterInHolyDays { get; set; } = new List<RosterInHolyDays>();

    public virtual ICollection<RosterInOfficeDays> RosterInOfficeDays { get; set; } = new List<RosterInOfficeDays>();

    public virtual Employees UpdatedByNavigation { get; set; }


    [ForeignKey("DepartmentHeadEmpID")]
    public virtual Employees DepartmentHeadEmpIDNavigation { get; set; }
}