// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class EmployeeBaseAllowance
{
    public int EmployeeBaseAllowanceId { get; set; }

    public int? EmployeeId { get; set; }

    public decimal? MobileInternetAllowance { get; set; }

    public bool IsMobileInternetAllowanceEnabled { get; set; }

    public decimal? ShiftAllowance { get; set; }

    public bool IsShiftAllowanceEnabled { get; set; }

    public decimal? HouseRentAllowancePercentage { get; set; }

    public bool IsHouseRentAllowancePercentageEnabled { get; set; }

    public decimal? MedicalAllowancePercentage { get; set; }

    public bool IsMedicalAllowancePercentageEnabled { get; set; }

    public decimal? ConveyanceAllowancePercentage { get; set; }

    public bool IsConveyanceAllowancePercentageEnabled { get; set; }

    public string Lip { get; set; }

    public string Lmac { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }

    public virtual Employee CreatedByNavigation { get; set; }

    public virtual Employee DeletedByNavigation { get; set; }

    public virtual Employee Employee { get; set; }

    public virtual Employee UpdatedByNavigation { get; set; }
}