// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class Employees
{
    public int EmployeeID { get; set; }

    public string? FirstName { get; set; }

    public string? LastName { get; set; }

    public string? FatherName { get; set; }

    public string? MotherName { get; set; }

    public string? MobileNumber { get; set; }

    public string? Email { get; set; }

    public string? BirthCertificateNo { get; set; }

    public string? TIN { get; set; }

    public DateOnly? DateOfBirth { get; set; }

    public string? AboutEmployee { get; set; }

    public string? NID { get; set; }

    public string? State { get; set; }

    public string? City { get; set; }

    public string? HouseNo { get; set; }

    public string? RoadNo { get; set; }

    public string? PostalCode { get; set; }

    public string? EmployeeImageFileName { get; set; }

    public string? EmployeeSignatureFileName { get; set; }

    public string? LIP { get; set; }

    public string? LMAC { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }

    public bool? HasUser { get; set; }

    public int? MaritalStatusID { get; set; }

    public int? GenderID { get; set; }

    public int? BloodGroupID { get; set; }

    public int? NationalityID { get; set; }

    public int? ReligionID { get; set; }

    public int? CountryID { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    public string? EmployeeCode { get; set; }

    public bool? IsActive { get; set; }

    public int? HeadID { get; set; }

    public virtual ICollection<ActionLogs> ActionLogs { get; set; } = new List<ActionLogs>();

    public virtual ICollection<AddressTypes> AddressTypesCreatedByNavigation { get; set; } = new List<AddressTypes>();

    public virtual ICollection<AddressTypes> AddressTypesDeletedByNavigation { get; set; } = new List<AddressTypes>();

    public virtual ICollection<AddressTypes> AddressTypesUpdatedByNavigation { get; set; } = new List<AddressTypes>();

    public virtual ICollection<Addresses> AddressesCreatedByNavigation { get; set; } = new List<Addresses>();

    public virtual ICollection<Addresses> AddressesDeletedByNavigation { get; set; } = new List<Addresses>();

    public virtual ICollection<Addresses> AddressesUpdatedByNavigation { get; set; } = new List<Addresses>();

    public virtual ICollection<AlertForEmployee> AlertForEmployeeCreatedByNavigation { get; set; } = new List<AlertForEmployee>();

    public virtual ICollection<AlertForEmployee> AlertForEmployeeDeletedByNavigation { get; set; } = new List<AlertForEmployee>();

    public virtual ICollection<AlertForEmployee> AlertForEmployeeEmployee { get; set; } = new List<AlertForEmployee>();

    public virtual ICollection<AlertForEmployee> AlertForEmployeeUpdatedByNavigation { get; set; } = new List<AlertForEmployee>();

    public virtual ICollection<Alerts> AlertsCreatedByNavigation { get; set; } = new List<Alerts>();

    public virtual ICollection<Alerts> AlertsDeletedByNavigation { get; set; } = new List<Alerts>();

    public virtual ICollection<Alerts> AlertsUpdatedByNavigation { get; set; } = new List<Alerts>();

    public virtual ICollection<AppSettings> AppSettingsCreatedByNavigation { get; set; } = new List<AppSettings>();

    public virtual ICollection<AppSettings> AppSettingsDeletedByNavigation { get; set; } = new List<AppSettings>();

    public virtual ICollection<AppSettings> AppSettingsUpdatedByNavigation { get; set; } = new List<AppSettings>();

    public virtual ICollection<ApprovalDesignation> ApprovalDesignationCreatedByNavigation { get; set; } = new List<ApprovalDesignation>();

    public virtual ICollection<ApprovalDesignation> ApprovalDesignationDeletedByNavigation { get; set; } = new List<ApprovalDesignation>();

    public virtual ICollection<ApprovalDesignation> ApprovalDesignationUpdatedByNavigation { get; set; } = new List<ApprovalDesignation>();

    public virtual ICollection<ApprovalSettings> ApprovalSettingsCreatedByNavigation { get; set; } = new List<ApprovalSettings>();

    public virtual ICollection<ApprovalSettings> ApprovalSettingsDeletedByNavigation { get; set; } = new List<ApprovalSettings>();

    public virtual ICollection<ApprovalSettings> ApprovalSettingsSelfExceptionApproval { get; set; } = new List<ApprovalSettings>();

    public virtual ICollection<ApprovalSettings> ApprovalSettingsUpdatedByNavigation { get; set; } = new List<ApprovalSettings>();

    public virtual ICollection<ApprovalTypes> ApprovalTypesCreatedByNavigation { get; set; } = new List<ApprovalTypes>();

    public virtual ICollection<ApprovalTypes> ApprovalTypesDeletedByNavigation { get; set; } = new List<ApprovalTypes>();

    public virtual ICollection<ApprovalTypes> ApprovalTypesUpdatedByNavigation { get; set; } = new List<ApprovalTypes>();

    public virtual ICollection<ApplicationUser> AspNetUsers { get; set; } = new List<ApplicationUser>();

    public virtual ICollection<Attendance> AttendanceCreatedByNavigation { get; set; } = new List<Attendance>();

    public virtual ICollection<Attendance> AttendanceDeletedByNavigation { get; set; } = new List<Attendance>();

    public virtual ICollection<Attendance> AttendanceEmployee { get; set; } = new List<Attendance>();

    public virtual ICollection<AttendanceLog> AttendanceLogCreatedByNavigation { get; set; } = new List<AttendanceLog>();

    public virtual ICollection<AttendanceLog> AttendanceLogDeletedByNavigation { get; set; } = new List<AttendanceLog>();

    public virtual ICollection<AttendanceLog> AttendanceLogUpdatedByNavigation { get; set; } = new List<AttendanceLog>();

    public virtual ICollection<AttendancePolicies> AttendancePoliciesCreatedByNavigation { get; set; } = new List<AttendancePolicies>();

    public virtual ICollection<AttendancePolicies> AttendancePoliciesDeletedByNavigation { get; set; } = new List<AttendancePolicies>();

    public virtual ICollection<AttendancePolicies> AttendancePoliciesUpdatedByNavigation { get; set; } = new List<AttendancePolicies>();

    public virtual ICollection<Attendance> AttendanceUpdatedByNavigation { get; set; } = new List<Attendance>();

    public virtual ICollection<AttributeNames> AttributeNamesCreatedByNavigation { get; set; } = new List<AttributeNames>();

    public virtual ICollection<AttributeNames> AttributeNamesDeletedByNavigation { get; set; } = new List<AttributeNames>();

    public virtual ICollection<AttributeNames> AttributeNamesUpdatedByNavigation { get; set; } = new List<AttributeNames>();

    public virtual ICollection<AttributeValues> AttributeValuesCreatedByNavigation { get; set; } = new List<AttributeValues>();

    public virtual ICollection<AttributeValues> AttributeValuesDeletedByNavigation { get; set; } = new List<AttributeValues>();

    public virtual ICollection<AttributeValues> AttributeValuesUpdatedByNavigation { get; set; } = new List<AttributeValues>();

    public virtual ICollection<BankAccountInfo> BankAccountInfoCreatedByNavigation { get; set; } = new List<BankAccountInfo>();

    public virtual ICollection<BankAccountInfo> BankAccountInfoDeletedByNavigation { get; set; } = new List<BankAccountInfo>();

    public virtual ICollection<BankAccountInfo> BankAccountInfoUpdatedByNavigation { get; set; } = new List<BankAccountInfo>();

    public virtual ICollection<BankBranches> BankBranchesCreatedByNavigation { get; set; } = new List<BankBranches>();

    public virtual ICollection<BankBranches> BankBranchesDeletedByNavigation { get; set; } = new List<BankBranches>();

    public virtual ICollection<BankBranches> BankBranchesUpdatedByNavigation { get; set; } = new List<BankBranches>();

    public virtual ICollection<Banks> BanksCreatedByNavigation { get; set; } = new List<Banks>();

    public virtual ICollection<Banks> BanksDeletedByNavigation { get; set; } = new List<Banks>();

    public virtual ICollection<Banks> BanksUpdatedByNavigation { get; set; } = new List<Banks>();

    public virtual ICollection<BarcodeGenerateFrom> BarcodeGenerateFromCreatedByNavigation { get; set; } = new List<BarcodeGenerateFrom>();

    public virtual ICollection<BarcodeGenerateFrom> BarcodeGenerateFromDeletedByNavigation { get; set; } = new List<BarcodeGenerateFrom>();

    public virtual ICollection<BarcodeGenerateFrom> BarcodeGenerateFromUpdatedByNavigation { get; set; } = new List<BarcodeGenerateFrom>();

    public virtual ICollection<BaseAccounts> BaseAccountsCreatedByNavigation { get; set; } = new List<BaseAccounts>();

    public virtual ICollection<BaseAccounts> BaseAccountsDeletedByNavigation { get; set; } = new List<BaseAccounts>();

    public virtual ICollection<BaseAccounts> BaseAccountsUpdatedByNavigation { get; set; } = new List<BaseAccounts>();

    public virtual ICollection<BenefitSetups> BenefitSetupsCreatedByNavigation { get; set; } = new List<BenefitSetups>();

    public virtual ICollection<BenefitSetups> BenefitSetupsDeletedByNavigation { get; set; } = new List<BenefitSetups>();

    public virtual ICollection<BenefitSetups> BenefitSetupsUpdatedByNavigation { get; set; } = new List<BenefitSetups>();

    public virtual ICollection<BenefitTypes> BenefitTypesCreatedByNavigation { get; set; } = new List<BenefitTypes>();

    public virtual ICollection<BenefitTypes> BenefitTypesDeletedByNavigation { get; set; } = new List<BenefitTypes>();

    public virtual ICollection<BenefitTypes> BenefitTypesUpdatedByNavigation { get; set; } = new List<BenefitTypes>();

    public virtual ICollection<Benefits> BenefitsCreatedByNavigation { get; set; } = new List<Benefits>();

    public virtual ICollection<Benefits> BenefitsDeletedByNavigation { get; set; } = new List<Benefits>();

    public virtual ICollection<Benefits> BenefitsUpdatedByNavigation { get; set; } = new List<Benefits>();

    public virtual BloodGroup? BloodGroup { get; set; }

    public virtual ICollection<BloodGroup> BloodGroupCreatedByNavigation { get; set; } = new List<BloodGroup>();

    public virtual ICollection<BloodGroup> BloodGroupDeletedByNavigation { get; set; } = new List<BloodGroup>();

    public virtual ICollection<BloodGroup> BloodGroupUpdatedByNavigation { get; set; } = new List<BloodGroup>();

    public virtual ICollection<CalculationTypes> CalculationTypesCreatedByNavigation { get; set; } = new List<CalculationTypes>();

    public virtual ICollection<CalculationTypes> CalculationTypesDeletedByNavigation { get; set; } = new List<CalculationTypes>();

    public virtual ICollection<CalculationTypes> CalculationTypesUpdatedByNavigation { get; set; } = new List<CalculationTypes>();

    public virtual ICollection<ChequeDetails> ChequeDetailsCreatedByNavigation { get; set; } = new List<ChequeDetails>();

    public virtual ICollection<ChequeDetails> ChequeDetailsDeletedByNavigation { get; set; } = new List<ChequeDetails>();

    public virtual ICollection<ChequeDetails> ChequeDetailsUpdatedByNavigation { get; set; } = new List<ChequeDetails>();

    public virtual ICollection<Classes> ClassesCreatedByNavigation { get; set; } = new List<Classes>();

    public virtual ICollection<Classes> ClassesDeletedByNavigation { get; set; } = new List<Classes>();

    public virtual ICollection<Classes> ClassesUpdatedByNavigation { get; set; } = new List<Classes>();

    public virtual ICollection<CompanyBranchAddresses> CompanyBranchAddressesCreatedByNavigation { get; set; } = new List<CompanyBranchAddresses>();

    public virtual ICollection<CompanyBranchAddresses> CompanyBranchAddressesDeletedByNavigation { get; set; } = new List<CompanyBranchAddresses>();

    public virtual ICollection<CompanyBranchAddresses> CompanyBranchAddressesUpdatedByNavigation { get; set; } = new List<CompanyBranchAddresses>();

    public virtual ICollection<CompanyBranches> CompanyBranchesCreatedByNavigation { get; set; } = new List<CompanyBranches>();

    public virtual ICollection<CompanyBranches> CompanyBranchesDeletedByNavigation { get; set; } = new List<CompanyBranches>();

    public virtual ICollection<CompanyBranches> CompanyBranchesUpdatedByNavigation { get; set; } = new List<CompanyBranches>();

    public virtual ICollection<CompanyWarehouseAddresses> CompanyWarehouseAddressesCreatedByNavigation { get; set; } = new List<CompanyWarehouseAddresses>();

    public virtual ICollection<CompanyWarehouseAddresses> CompanyWarehouseAddressesDeletedByNavigation { get; set; } = new List<CompanyWarehouseAddresses>();

    public virtual ICollection<CompanyWarehouseAddresses> CompanyWarehouseAddressesUpdatedByNavigation { get; set; } = new List<CompanyWarehouseAddresses>();

    public virtual ICollection<CompanyWarehouses> CompanyWarehousesCreatedByNavigation { get; set; } = new List<CompanyWarehouses>();

    public virtual ICollection<CompanyWarehouses> CompanyWarehousesDeletedByNavigation { get; set; } = new List<CompanyWarehouses>();

    public virtual ICollection<CompanyWarehouses> CompanyWarehousesUpdatedByNavigation { get; set; } = new List<CompanyWarehouses>();

    public virtual ICollection<CompensationDayExchanges> CompensationDayExchangesCreatedByNavigation { get; set; } = new List<CompensationDayExchanges>();

    public virtual ICollection<CompensationDayExchanges> CompensationDayExchangesDeletedByNavigation { get; set; } = new List<CompensationDayExchanges>();

    public virtual ICollection<CompensationDayExchanges> CompensationDayExchangesUpdatedByNavigation { get; set; } = new List<CompensationDayExchanges>();

    public virtual ICollection<CompensationTypes> CompensationTypesCreatedByNavigation { get; set; } = new List<CompensationTypes>();

    public virtual ICollection<CompensationTypes> CompensationTypesDeletedByNavigation { get; set; } = new List<CompensationTypes>();

    public virtual ICollection<CompensationTypes> CompensationTypesUpdatedByNavigation { get; set; } = new List<CompensationTypes>();

    public virtual Country? Country { get; set; }

    public virtual ICollection<Country> CountryCreatedByNavigation { get; set; } = new List<Country>();

    public virtual ICollection<Country> CountryDeletedByNavigation { get; set; } = new List<Country>();

    public virtual ICollection<Country> CountryUpdatedByNavigation { get; set; } = new List<Country>();

    public virtual Employees? CreatedByNavigation { get; set; }

    public virtual ICollection<CreditNote> CreditNoteCreatedByNavigation { get; set; } = new List<CreditNote>();

    public virtual ICollection<CreditNote> CreditNoteDeletedByNavigation { get; set; } = new List<CreditNote>();

    public virtual ICollection<CreditNoteItems> CreditNoteItemsCreatedByNavigation { get; set; } = new List<CreditNoteItems>();

    public virtual ICollection<CreditNoteItems> CreditNoteItemsDeletedByNavigation { get; set; } = new List<CreditNoteItems>();

    public virtual ICollection<CreditNoteItems> CreditNoteItemsUpdatedByNavigation { get; set; } = new List<CreditNoteItems>();

    public virtual ICollection<CreditNote> CreditNoteUpdatedByNavigation { get; set; } = new List<CreditNote>();

    public virtual ICollection<Currencies> CurrenciesCreatedByNavigation { get; set; } = new List<Currencies>();

    public virtual ICollection<Currencies> CurrenciesDeletedByNavigation { get; set; } = new List<Currencies>();

    public virtual ICollection<Currencies> CurrenciesUpdatedByNavigation { get; set; } = new List<Currencies>();

    public virtual ICollection<CustomerAddresses> CustomerAddressesCreatedByNavigation { get; set; } = new List<CustomerAddresses>();

    public virtual ICollection<CustomerAddresses> CustomerAddressesDeletedByNavigation { get; set; } = new List<CustomerAddresses>();

    public virtual ICollection<CustomerAddresses> CustomerAddressesUpdatedByNavigation { get; set; } = new List<CustomerAddresses>();

    public virtual ICollection<CustomerGroup> CustomerGroupCreatedByNavigation { get; set; } = new List<CustomerGroup>();

    public virtual ICollection<CustomerGroup> CustomerGroupDeletedByNavigation { get; set; } = new List<CustomerGroup>();

    public virtual ICollection<CustomerGroup> CustomerGroupUpdatedByNavigation { get; set; } = new List<CustomerGroup>();

    public virtual ICollection<Customers> CustomersCreatedByNavigation { get; set; } = new List<Customers>();

    public virtual ICollection<Customers> CustomersDeletedByNavigation { get; set; } = new List<Customers>();

    public virtual ICollection<Customers> CustomersUpdatedByNavigation { get; set; } = new List<Customers>();

    public virtual ICollection<DailyAttendanceStatus> DailyAttendanceStatusCreatedByNavigation { get; set; } = new List<DailyAttendanceStatus>();

    public virtual ICollection<DailyAttendanceStatus> DailyAttendanceStatusEmployee { get; set; } = new List<DailyAttendanceStatus>();

    public virtual ICollection<DailyAttendanceStatus> DailyAttendanceStatusUpdatedByNavigation { get; set; } = new List<DailyAttendanceStatus>();

    public virtual ICollection<DebitNote> DebitNoteCreatedByNavigation { get; set; } = new List<DebitNote>();

    public virtual ICollection<DebitNote> DebitNoteDeletedByNavigation { get; set; } = new List<DebitNote>();

    public virtual ICollection<DebitNoteItems> DebitNoteItemsCreatedByNavigation { get; set; } = new List<DebitNoteItems>();

    public virtual ICollection<DebitNoteItems> DebitNoteItemsDeletedByNavigation { get; set; } = new List<DebitNoteItems>();

    public virtual ICollection<DebitNoteItems> DebitNoteItemsUpdatedByNavigation { get; set; } = new List<DebitNoteItems>();

    public virtual ICollection<DebitNote> DebitNoteUpdatedByNavigation { get; set; } = new List<DebitNote>();

    public virtual ICollection<DefaultShifts> DefaultShiftsCreatedByNavigation { get; set; } = new List<DefaultShifts>();

    public virtual ICollection<DefaultShifts> DefaultShiftsDeletedByNavigation { get; set; } = new List<DefaultShifts>();

    public virtual ICollection<DefaultShifts> DefaultShiftsEmployee { get; set; } = new List<DefaultShifts>();

    public virtual ICollection<DefaultShifts> DefaultShiftsUpdatedByNavigation { get; set; } = new List<DefaultShifts>();

    public virtual ICollection<Degree> DegreeCreatedByNavigation { get; set; } = new List<Degree>();

    public virtual ICollection<Degree> DegreeDeletedByNavigation { get; set; } = new List<Degree>();

    public virtual ICollection<Degree> DegreeUpdatedByNavigation { get; set; } = new List<Degree>();

    public virtual Employees? DeletedByNavigation { get; set; }

    public virtual ICollection<Departments> DepartmentsCreatedByNavigation { get; set; } = new List<Departments>();

    public virtual ICollection<Departments> DepartmentsDeletedByNavigation { get; set; } = new List<Departments>();

    public virtual ICollection<Departments> DepartmentsDepartmentHeadEmp { get; set; } = new List<Departments>();

    public virtual ICollection<Departments> DepartmentsUpdatedByNavigation { get; set; } = new List<Departments>();

    public virtual ICollection<Designations> DesignationsCreatedByNavigation { get; set; } = new List<Designations>();

    public virtual ICollection<Designations> DesignationsDeletedByNavigation { get; set; } = new List<Designations>();

    public virtual ICollection<Designations> DesignationsUpdatedByNavigation { get; set; } = new List<Designations>();

    public virtual ICollection<EducationBoard> EducationBoardDeletedByNavigation { get; set; } = new List<EducationBoard>();

    public virtual ICollection<EducationBoard> EducationBoardUpdatedByNavigation { get; set; } = new List<EducationBoard>();

    public virtual ICollection<EducationLevels> EducationLevelsCreatedByNavigation { get; set; } = new List<EducationLevels>();

    public virtual ICollection<EducationLevels> EducationLevelsDeletedByNavigation { get; set; } = new List<EducationLevels>();

    public virtual ICollection<EducationLevels> EducationLevelsUpdatedByNavigation { get; set; } = new List<EducationLevels>();

    public virtual ICollection<EmailSettings> EmailSettingsCreatedByNavigation { get; set; } = new List<EmailSettings>();

    public virtual ICollection<EmailSettings> EmailSettingsDeletedByNavigation { get; set; } = new List<EmailSettings>();

    public virtual ICollection<EmailSettings> EmailSettingsUpdatedByNavigation { get; set; } = new List<EmailSettings>();

    public virtual ICollection<EmployeeActionTypes> EmployeeActionTypesCreatedByNavigation { get; set; } = new List<EmployeeActionTypes>();

    public virtual ICollection<EmployeeActionTypes> EmployeeActionTypesDeletedByNavigation { get; set; } = new List<EmployeeActionTypes>();

    public virtual ICollection<EmployeeActionTypes> EmployeeActionTypesUpdatedByNavigation { get; set; } = new List<EmployeeActionTypes>();

    public virtual ICollection<EmployeeAdditionalInfo> EmployeeAdditionalInfoCreatedByNavigation { get; set; } = new List<EmployeeAdditionalInfo>();

    public virtual ICollection<EmployeeAdditionalInfo> EmployeeAdditionalInfoDeletedByNavigation { get; set; } = new List<EmployeeAdditionalInfo>();

    public virtual ICollection<EmployeeAdditionalInfo> EmployeeAdditionalInfoEmployee { get; set; } = new List<EmployeeAdditionalInfo>();

    public virtual ICollection<EmployeeAdditionalInfo> EmployeeAdditionalInfoUpdatedByNavigation { get; set; } = new List<EmployeeAdditionalInfo>();

    public virtual ICollection<EmployeeAdvances> EmployeeAdvancesApprovedByUser { get; set; } = new List<EmployeeAdvances>();

    public virtual ICollection<EmployeeAdvances> EmployeeAdvancesCreatedByNavigation { get; set; } = new List<EmployeeAdvances>();

    public virtual ICollection<EmployeeAdvances> EmployeeAdvancesDeletedByNavigation { get; set; } = new List<EmployeeAdvances>();

    public virtual ICollection<EmployeeAdvances> EmployeeAdvancesRequestedByUser { get; set; } = new List<EmployeeAdvances>();

    public virtual ICollection<EmployeeAdvances> EmployeeAdvancesUpdatedByNavigation { get; set; } = new List<EmployeeAdvances>();

    public virtual ICollection<EmployeeAllowanceSetup> EmployeeAllowanceSetupCreatedByNavigation { get; set; } = new List<EmployeeAllowanceSetup>();

    public virtual ICollection<EmployeeAllowanceSetup> EmployeeAllowanceSetupDeletedByNavigation { get; set; } = new List<EmployeeAllowanceSetup>();

    public virtual ICollection<EmployeeAllowanceSetup> EmployeeAllowanceSetupUpdatedByNavigation { get; set; } = new List<EmployeeAllowanceSetup>();

    public virtual ICollection<EmployeeAllowanceTypes> EmployeeAllowanceTypesDeletedByNavigation { get; set; } = new List<EmployeeAllowanceTypes>();

    public virtual ICollection<EmployeeAllowanceTypes> EmployeeAllowanceTypesUpdatedByNavigation { get; set; } = new List<EmployeeAllowanceTypes>();

    public virtual ICollection<EmployeeAllowances> EmployeeAllowancesCreatedByNavigation { get; set; } = new List<EmployeeAllowances>();

    public virtual ICollection<EmployeeAllowances> EmployeeAllowancesDeletedByNavigation { get; set; } = new List<EmployeeAllowances>();

    public virtual ICollection<EmployeeAllowances> EmployeeAllowancesUpdatedByNavigation { get; set; } = new List<EmployeeAllowances>();

    public virtual ICollection<EmployeeBaseAllowances> EmployeeBaseAllowancesCreatedByNavigation { get; set; } = new List<EmployeeBaseAllowances>();

    public virtual ICollection<EmployeeBaseAllowances> EmployeeBaseAllowancesDeletedByNavigation { get; set; } = new List<EmployeeBaseAllowances>();

    public virtual ICollection<EmployeeBaseAllowances> EmployeeBaseAllowancesEmployee { get; set; } = new List<EmployeeBaseAllowances>();

    public virtual ICollection<EmployeeBaseAllowances> EmployeeBaseAllowancesUpdatedByNavigation { get; set; } = new List<EmployeeBaseAllowances>();

    public virtual ICollection<EmployeeBaseBenefits> EmployeeBaseBenefitsCreatedByNavigation { get; set; } = new List<EmployeeBaseBenefits>();

    public virtual ICollection<EmployeeBaseBenefits> EmployeeBaseBenefitsDeletedByNavigation { get; set; } = new List<EmployeeBaseBenefits>();

    public virtual ICollection<EmployeeBaseBenefits> EmployeeBaseBenefitsEmployee { get; set; } = new List<EmployeeBaseBenefits>();

    public virtual ICollection<EmployeeBaseBenefits> EmployeeBaseBenefitsUpdatedByNavigation { get; set; } = new List<EmployeeBaseBenefits>();

    public virtual ICollection<EmployeeBasePaymentModes> EmployeeBasePaymentModesCreatedByNavigation { get; set; } = new List<EmployeeBasePaymentModes>();

    public virtual ICollection<EmployeeBasePaymentModes> EmployeeBasePaymentModesDeletedByNavigation { get; set; } = new List<EmployeeBasePaymentModes>();

    public virtual ICollection<EmployeeBasePaymentModes> EmployeeBasePaymentModesEmployee { get; set; } = new List<EmployeeBasePaymentModes>();

    public virtual ICollection<EmployeeBasePaymentModes> EmployeeBasePaymentModesUpdatedByNavigation { get; set; } = new List<EmployeeBasePaymentModes>();

    public virtual ICollection<EmployeeBenefits> EmployeeBenefitsCreatedByNavigation { get; set; } = new List<EmployeeBenefits>();

    public virtual ICollection<EmployeeBenefits> EmployeeBenefitsDeletedByNavigation { get; set; } = new List<EmployeeBenefits>();

    public virtual ICollection<EmployeeBenefits> EmployeeBenefitsUpdatedByNavigation { get; set; } = new List<EmployeeBenefits>();

    public virtual ICollection<EmployeeCareerChangeHistory> EmployeeCareerChangeHistoryApprovalPerson { get; set; } = new List<EmployeeCareerChangeHistory>();

    public virtual ICollection<EmployeeCareerChangeHistory> EmployeeCareerChangeHistoryCreatedByNavigation { get; set; } = new List<EmployeeCareerChangeHistory>();

    public virtual ICollection<EmployeeCareerChangeHistory> EmployeeCareerChangeHistoryDeletedByNavigation { get; set; } = new List<EmployeeCareerChangeHistory>();

    public virtual ICollection<EmployeeCareerChangeHistory> EmployeeCareerChangeHistoryEmployee { get; set; } = new List<EmployeeCareerChangeHistory>();

    public virtual ICollection<EmployeeCareerChangeHistory> EmployeeCareerChangeHistoryUpdatedByNavigation { get; set; } = new List<EmployeeCareerChangeHistory>();

    public virtual ICollection<EmployeeCareerChanges> EmployeeCareerChangesApprovalPerson { get; set; } = new List<EmployeeCareerChanges>();

    public virtual ICollection<EmployeeCareerChanges> EmployeeCareerChangesCreatedByNavigation { get; set; } = new List<EmployeeCareerChanges>();

    public virtual ICollection<EmployeeCareerChanges> EmployeeCareerChangesDeletedByNavigation { get; set; } = new List<EmployeeCareerChanges>();

    public virtual ICollection<EmployeeCareerChanges> EmployeeCareerChangesEmployee { get; set; } = new List<EmployeeCareerChanges>();

    public virtual ICollection<EmployeeCareerChanges> EmployeeCareerChangesUpdatedByNavigation { get; set; } = new List<EmployeeCareerChanges>();

    public virtual ICollection<EmployeeEducationalInfo> EmployeeEducationalInfoCreatedByNavigation { get; set; } = new List<EmployeeEducationalInfo>();

    public virtual ICollection<EmployeeEducationalInfo> EmployeeEducationalInfoDeletedByNavigation { get; set; } = new List<EmployeeEducationalInfo>();

    public virtual ICollection<EmployeeEducationalInfo> EmployeeEducationalInfoEmployee { get; set; } = new List<EmployeeEducationalInfo>();

    public virtual ICollection<EmployeeEducationalInfo> EmployeeEducationalInfoUpdatedByNavigation { get; set; } = new List<EmployeeEducationalInfo>();

    public virtual ICollection<EmployeeEmeContacts> EmployeeEmeContactsCreatedByNavigation { get; set; } = new List<EmployeeEmeContacts>();

    public virtual ICollection<EmployeeEmeContacts> EmployeeEmeContactsDeletedByNavigation { get; set; } = new List<EmployeeEmeContacts>();

    public virtual ICollection<EmployeeEmeContacts> EmployeeEmeContactsEmployee { get; set; } = new List<EmployeeEmeContacts>();

    public virtual ICollection<EmployeeEmeContacts> EmployeeEmeContactsUpdatedByNavigation { get; set; } = new List<EmployeeEmeContacts>();

    public virtual ICollection<EmployeeFamilyInfo> EmployeeFamilyInfoCreatedByNavigation { get; set; } = new List<EmployeeFamilyInfo>();

    public virtual ICollection<EmployeeFamilyInfo> EmployeeFamilyInfoDeletedByNavigation { get; set; } = new List<EmployeeFamilyInfo>();

    public virtual ICollection<EmployeeFamilyInfo> EmployeeFamilyInfoEmployee { get; set; } = new List<EmployeeFamilyInfo>();

    public virtual ICollection<EmployeeFamilyInfo> EmployeeFamilyInfoUpdatedByNavigation { get; set; } = new List<EmployeeFamilyInfo>();

    public virtual ICollection<EmployeeFinalShifts> EmployeeFinalShiftsCreatedByNavigation { get; set; } = new List<EmployeeFinalShifts>();

    public virtual ICollection<EmployeeFinalShifts> EmployeeFinalShiftsDeletedByNavigation { get; set; } = new List<EmployeeFinalShifts>();

    public virtual ICollection<EmployeeFinalShifts> EmployeeFinalShiftsEmployee { get; set; } = new List<EmployeeFinalShifts>();

    public virtual ICollection<EmployeeFinalShifts> EmployeeFinalShiftsUpdatedByNavigation { get; set; } = new List<EmployeeFinalShifts>();

    public virtual ICollection<EmployeeOfficeInfo> EmployeeOfficeInfoCreatedByNavigation { get; set; } = new List<EmployeeOfficeInfo>();

    public virtual ICollection<EmployeeOfficeInfo> EmployeeOfficeInfoDeletedByNavigation { get; set; } = new List<EmployeeOfficeInfo>();

    public virtual ICollection<EmployeeOfficeInfo> EmployeeOfficeInfoEmployee { get; set; } = new List<EmployeeOfficeInfo>();

    public virtual ICollection<EmployeeOfficeInfo> EmployeeOfficeInfoHeadOfDepartment { get; set; } = new List<EmployeeOfficeInfo>();

    public virtual ICollection<EmployeeOfficeInfo> EmployeeOfficeInfoImmediateSupervisor { get; set; } = new List<EmployeeOfficeInfo>();

    public virtual ICollection<EmployeeOfficeInfo> EmployeeOfficeInfoSeniorSupervisor { get; set; } = new List<EmployeeOfficeInfo>();

    public virtual ICollection<EmployeeOfficeInfo> EmployeeOfficeInfoUpdatedByNavigation { get; set; } = new List<EmployeeOfficeInfo>();

    public virtual ICollection<EmployeeSalarySettings> EmployeeSalarySettingsCreatedByNavigation { get; set; } = new List<EmployeeSalarySettings>();

    public virtual ICollection<EmployeeSalarySettings> EmployeeSalarySettingsDeletedByNavigation { get; set; } = new List<EmployeeSalarySettings>();

    public virtual ICollection<EmployeeSalarySettings> EmployeeSalarySettingsEmployee { get; set; } = new List<EmployeeSalarySettings>();

    public virtual ICollection<EmployeeSalarySettings> EmployeeSalarySettingsUpdatedByNavigation { get; set; } = new List<EmployeeSalarySettings>();

    public virtual ICollection<EmployeeTranningInfo> EmployeeTranningInfoCreatedByNavigation { get; set; } = new List<EmployeeTranningInfo>();

    public virtual ICollection<EmployeeTranningInfo> EmployeeTranningInfoDeletedByNavigation { get; set; } = new List<EmployeeTranningInfo>();

    public virtual ICollection<EmployeeTranningInfo> EmployeeTranningInfoEmployee { get; set; } = new List<EmployeeTranningInfo>();

    public virtual ICollection<EmployeeTranningInfo> EmployeeTranningInfoUpdatedByNavigation { get; set; } = new List<EmployeeTranningInfo>();

    public virtual ICollection<EmployeeTransfer> EmployeeTransferApprovalPerson { get; set; } = new List<EmployeeTransfer>();

    public virtual ICollection<EmployeeTransfer> EmployeeTransferCreatedByNavigation { get; set; } = new List<EmployeeTransfer>();

    public virtual ICollection<EmployeeTransfer> EmployeeTransferDeletedByNavigation { get; set; } = new List<EmployeeTransfer>();

    public virtual ICollection<EmployeeTransfer> EmployeeTransferEmployee { get; set; } = new List<EmployeeTransfer>();

    public virtual ICollection<EmployeeTransferHistory> EmployeeTransferHistoryApprovalPerson { get; set; } = new List<EmployeeTransferHistory>();

    public virtual ICollection<EmployeeTransferHistory> EmployeeTransferHistoryCreatedByNavigation { get; set; } = new List<EmployeeTransferHistory>();

    public virtual ICollection<EmployeeTransferHistory> EmployeeTransferHistoryDeletedByNavigation { get; set; } = new List<EmployeeTransferHistory>();

    public virtual ICollection<EmployeeTransferHistory> EmployeeTransferHistoryUpdatedByNavigation { get; set; } = new List<EmployeeTransferHistory>();

    public virtual ICollection<EmployeeTransfer> EmployeeTransferUpdatedByNavigation { get; set; } = new List<EmployeeTransfer>();

    public virtual ICollection<EmployeeType> EmployeeTypeCreatedByNavigation { get; set; } = new List<EmployeeType>();

    public virtual ICollection<EmployeeType> EmployeeTypeDeletedByNavigation { get; set; } = new List<EmployeeType>();

    public virtual ICollection<EmployeeType> EmployeeTypeUpdatedByNavigation { get; set; } = new List<EmployeeType>();

    public virtual ICollection<EmploymentNature> EmploymentNatureCreatedByNavigation { get; set; } = new List<EmploymentNature>();

    public virtual ICollection<EmploymentNature> EmploymentNatureDeletedByNavigation { get; set; } = new List<EmploymentNature>();

    public virtual ICollection<EmploymentNature> EmploymentNatureUpdatedByNavigation { get; set; } = new List<EmploymentNature>();

    public virtual ICollection<FinancialYears> FinancialYearsCreatedByNavigation { get; set; } = new List<FinancialYears>();

    public virtual ICollection<FinancialYears> FinancialYearsDeletedByNavigation { get; set; } = new List<FinancialYears>();

    public virtual ICollection<FinancialYears> FinancialYearsUpdatedByNavigation { get; set; } = new List<FinancialYears>();

    public virtual Genders? Gender { get; set; }

    public virtual ICollection<Genders> GendersCreatedByNavigation { get; set; } = new List<Genders>();

    public virtual ICollection<Genders> GendersDeletedByNavigation { get; set; } = new List<Genders>();

    public virtual ICollection<Genders> GendersUpdatedByNavigation { get; set; } = new List<Genders>();

    public virtual ICollection<Grade> GradeCreatedByNavigation { get; set; } = new List<Grade>();

    public virtual ICollection<Grade> GradeDeletedByNavigation { get; set; } = new List<Grade>();

    public virtual ICollection<Grade> GradeUpdatedByNavigation { get; set; } = new List<Grade>();

    public virtual Heads? Head { get; set; }

    public virtual ICollection<HeadDetails> HeadDetailsCreatedByNavigation { get; set; } = new List<HeadDetails>();

    public virtual ICollection<HeadDetails> HeadDetailsDeletedByNavigation { get; set; } = new List<HeadDetails>();

    public virtual ICollection<HeadDetails> HeadDetailsUpdatedByNavigation { get; set; } = new List<HeadDetails>();

    public virtual ICollection<Heads> HeadsCreatedByNavigation { get; set; } = new List<Heads>();

    public virtual ICollection<Heads> HeadsDeletedByNavigation { get; set; } = new List<Heads>();

    public virtual ICollection<Heads> HeadsUpdatedByNavigation { get; set; } = new List<Heads>();

    public virtual ICollection<Holidays> HolidaysCreatedByNavigation { get; set; } = new List<Holidays>();

    public virtual ICollection<Holidays> HolidaysDeletedByNavigation { get; set; } = new List<Holidays>();

    public virtual ICollection<Holidays> HolidaysUpdatedByNavigation { get; set; } = new List<Holidays>();

    public virtual ICollection<Inventory> InventoryCreatedByNavigation { get; set; } = new List<Inventory>();

    public virtual ICollection<Inventory> InventoryDeletedByNavigation { get; set; } = new List<Inventory>();

    public virtual ICollection<InventoryTransactionHistory> InventoryTransactionHistoryCreatedByNavigation { get; set; } = new List<InventoryTransactionHistory>();

    public virtual ICollection<InventoryTransactionHistory> InventoryTransactionHistoryDeletedByNavigation { get; set; } = new List<InventoryTransactionHistory>();

    public virtual ICollection<InventoryTransactionHistory> InventoryTransactionHistoryUpdatedByNavigation { get; set; } = new List<InventoryTransactionHistory>();

    public virtual ICollection<InventoryTransfers> InventoryTransfersCreatedByNavigation { get; set; } = new List<InventoryTransfers>();

    public virtual ICollection<InventoryTransfers> InventoryTransfersDeletedByNavigation { get; set; } = new List<InventoryTransfers>();

    public virtual ICollection<InventoryTransfers> InventoryTransfersUpdatedByNavigation { get; set; } = new List<InventoryTransfers>();

    public virtual ICollection<Inventory> InventoryUpdatedByNavigation { get; set; } = new List<Inventory>();

    public virtual ICollection<Employees> InverseCreatedByNavigation { get; set; } = new List<Employees>();

    public virtual ICollection<Employees> InverseDeletedByNavigation { get; set; } = new List<Employees>();

    public virtual ICollection<Employees> InverseUpdatedByNavigation { get; set; } = new List<Employees>();

    public virtual ICollection<InvoiceBaseCAddresses> InvoiceBaseCAddressesCreatedByNavigation { get; set; } = new List<InvoiceBaseCAddresses>();

    public virtual ICollection<InvoiceBaseCAddresses> InvoiceBaseCAddressesDeletedByNavigation { get; set; } = new List<InvoiceBaseCAddresses>();

    public virtual ICollection<InvoiceBaseCAddresses> InvoiceBaseCAddressesUpdatedByNavigation { get; set; } = new List<InvoiceBaseCAddresses>();

    public virtual ICollection<InvoiceItems> InvoiceItemsCreatedByNavigation { get; set; } = new List<InvoiceItems>();

    public virtual ICollection<InvoiceItems> InvoiceItemsDeletedByNavigation { get; set; } = new List<InvoiceItems>();

    public virtual ICollection<InvoiceItems> InvoiceItemsUpdatedByNavigation { get; set; } = new List<InvoiceItems>();

    public virtual ICollection<Invoices> InvoicesCreatedByNavigation { get; set; } = new List<Invoices>();

    public virtual ICollection<Invoices> InvoicesDeletedByNavigation { get; set; } = new List<Invoices>();

    public virtual ICollection<Invoices> InvoicesUpdatedByNavigation { get; set; } = new List<Invoices>();

    public virtual ICollection<JobTeamActivities> JobTeamActivitiesCreatedByNavigation { get; set; } = new List<JobTeamActivities>();

    public virtual ICollection<JobTeamActivities> JobTeamActivitiesDeletedByNavigation { get; set; } = new List<JobTeamActivities>();

    public virtual ICollection<JobTeamActivities> JobTeamActivitiesUpdatedByNavigation { get; set; } = new List<JobTeamActivities>();

    public virtual ICollection<JobTeams> JobTeamsCreatedByNavigation { get; set; } = new List<JobTeams>();

    public virtual ICollection<JobTeams> JobTeamsDeletedByNavigation { get; set; } = new List<JobTeams>();

    public virtual ICollection<JobTeams> JobTeamsEmployee { get; set; } = new List<JobTeams>();

    public virtual ICollection<JobTeams> JobTeamsUpdatedByNavigation { get; set; } = new List<JobTeams>();

    public virtual ICollection<JobTypes> JobTypesCreatedByNavigation { get; set; } = new List<JobTypes>();

    public virtual ICollection<JobTypes> JobTypesDeletedByNavigation { get; set; } = new List<JobTypes>();

    public virtual ICollection<JobTypes> JobTypesUpdatedByNavigation { get; set; } = new List<JobTypes>();

    public virtual ICollection<Jobs> JobsCreatedByNavigation { get; set; } = new List<Jobs>();

    public virtual ICollection<Jobs> JobsDeletedByNavigation { get; set; } = new List<Jobs>();

    public virtual ICollection<Jobs> JobsUpdatedByNavigation { get; set; } = new List<Jobs>();

    public virtual ICollection<JournalDetails> JournalDetailsCreatedByNavigation { get; set; } = new List<JournalDetails>();

    public virtual ICollection<JournalDetails> JournalDetailsDeletedByNavigation { get; set; } = new List<JournalDetails>();

    public virtual ICollection<JournalDetails> JournalDetailsUpdatedByNavigation { get; set; } = new List<JournalDetails>();

    public virtual ICollection<JournalHeadTbls> JournalHeadTblsCreatedByNavigation { get; set; } = new List<JournalHeadTbls>();

    public virtual ICollection<JournalHeadTbls> JournalHeadTblsDeletedByNavigation { get; set; } = new List<JournalHeadTbls>();

    public virtual ICollection<JournalHeadTbls> JournalHeadTblsUpdatedByNavigation { get; set; } = new List<JournalHeadTbls>();

    public virtual ICollection<JournalHeads> JournalHeadsCreatedByNavigation { get; set; } = new List<JournalHeads>();

    public virtual ICollection<JournalHeads> JournalHeadsDeletedByNavigation { get; set; } = new List<JournalHeads>();

    public virtual ICollection<JournalHeads> JournalHeadsUpdatedByNavigation { get; set; } = new List<JournalHeads>();

    public virtual ICollection<JournalTypes> JournalTypesCreatedByNavigation { get; set; } = new List<JournalTypes>();

    public virtual ICollection<JournalTypes> JournalTypesDeletedByNavigation { get; set; } = new List<JournalTypes>();

    public virtual ICollection<JournalTypes> JournalTypesUpdatedByNavigation { get; set; } = new List<JournalTypes>();

    public virtual ICollection<Journals> JournalsCreatedByNavigation { get; set; } = new List<Journals>();

    public virtual ICollection<Journals> JournalsDeletedByNavigation { get; set; } = new List<Journals>();

    public virtual ICollection<Journals> JournalsUpdatedByNavigation { get; set; } = new List<Journals>();

    public virtual ICollection<LeadActivityTypes> LeadActivityTypesCreatedByNavigation { get; set; } = new List<LeadActivityTypes>();

    public virtual ICollection<LeadActivityTypes> LeadActivityTypesDeletedByNavigation { get; set; } = new List<LeadActivityTypes>();

    public virtual ICollection<LeadActivityTypes> LeadActivityTypesUpdatedByNavigation { get; set; } = new List<LeadActivityTypes>();

    public virtual ICollection<LeadDetails> LeadDetailsCreatedByNavigation { get; set; } = new List<LeadDetails>();

    public virtual ICollection<LeadDetails> LeadDetailsDeletedByNavigation { get; set; } = new List<LeadDetails>();

    public virtual ICollection<LeadDetails> LeadDetailsUpdatedByNavigation { get; set; } = new List<LeadDetails>();

    public virtual ICollection<LeadProjectTeamMembers> LeadProjectTeamMembersCreatedByNavigation { get; set; } = new List<LeadProjectTeamMembers>();

    public virtual ICollection<LeadProjectTeamMembers> LeadProjectTeamMembersDeletedByNavigation { get; set; } = new List<LeadProjectTeamMembers>();

    public virtual ICollection<LeadProjectTeamMembers> LeadProjectTeamMembersEmployee { get; set; } = new List<LeadProjectTeamMembers>();

    public virtual ICollection<LeadProjectTeamMembers> LeadProjectTeamMembersUpdatedByNavigation { get; set; } = new List<LeadProjectTeamMembers>();

    public virtual ICollection<LeadProjectTeams> LeadProjectTeamsCreatedByNavigation { get; set; } = new List<LeadProjectTeams>();

    public virtual ICollection<LeadProjectTeams> LeadProjectTeamsDeletedByNavigation { get; set; } = new List<LeadProjectTeams>();

    public virtual ICollection<LeadProjectTeams> LeadProjectTeamsUpdatedByNavigation { get; set; } = new List<LeadProjectTeams>();

    public virtual ICollection<LeadServices> LeadServicesCreatedByNavigation { get; set; } = new List<LeadServices>();

    public virtual ICollection<LeadServices> LeadServicesDeletedByNavigation { get; set; } = new List<LeadServices>();

    public virtual ICollection<LeadServices> LeadServicesUpdatedByNavigation { get; set; } = new List<LeadServices>();

    public virtual ICollection<LeadSources> LeadSourcesCreatedByNavigation { get; set; } = new List<LeadSources>();

    public virtual ICollection<LeadSources> LeadSourcesDeletedByNavigation { get; set; } = new List<LeadSources>();

    public virtual ICollection<LeadSources> LeadSourcesUpdatedByNavigation { get; set; } = new List<LeadSources>();

    public virtual ICollection<LeadStatuses> LeadStatusesCreatedByNavigation { get; set; } = new List<LeadStatuses>();

    public virtual ICollection<LeadStatuses> LeadStatusesDeletedByNavigation { get; set; } = new List<LeadStatuses>();

    public virtual ICollection<LeadStatuses> LeadStatusesUpdatedByNavigation { get; set; } = new List<LeadStatuses>();

    public virtual ICollection<LeadTypes> LeadTypesCreatedByNavigation { get; set; } = new List<LeadTypes>();

    public virtual ICollection<LeadTypes> LeadTypesDeletedByNavigation { get; set; } = new List<LeadTypes>();

    public virtual ICollection<LeadTypes> LeadTypesUpdatedByNavigation { get; set; } = new List<LeadTypes>();

    public virtual ICollection<Leads> LeadsCreatedByNavigation { get; set; } = new List<Leads>();

    public virtual ICollection<Leads> LeadsDeletedByNavigation { get; set; } = new List<Leads>();

    public virtual ICollection<Leads> LeadsLeadOwner { get; set; } = new List<Leads>();

    public virtual ICollection<Leads> LeadsUpdatedByNavigation { get; set; } = new List<Leads>();

    public virtual ICollection<LeaveApplications> LeaveApplicationsApprovalPerson { get; set; } = new List<LeaveApplications>();

    public virtual ICollection<LeaveApplications> LeaveApplicationsCreatedByNavigation { get; set; } = new List<LeaveApplications>();

    public virtual ICollection<LeaveApplications> LeaveApplicationsDeletedByNavigation { get; set; } = new List<LeaveApplications>();

    public virtual ICollection<LeaveApplications> LeaveApplicationsEmployee { get; set; } = new List<LeaveApplications>();

    public virtual ICollection<LeaveApplications> LeaveApplicationsUpdatedByNavigation { get; set; } = new List<LeaveApplications>();

    public virtual ICollection<LeaveBalances> LeaveBalancesCreatedByNavigation { get; set; } = new List<LeaveBalances>();

    public virtual ICollection<LeaveBalances> LeaveBalancesDeletedByNavigation { get; set; } = new List<LeaveBalances>();

    public virtual ICollection<LeaveBalances> LeaveBalancesEmployee { get; set; } = new List<LeaveBalances>();

    public virtual ICollection<LeaveBalances> LeaveBalancesUpdatedByNavigation { get; set; } = new List<LeaveBalances>();

    public virtual ICollection<LeaveBaseApprovalHistory> LeaveBaseApprovalHistoryApproveByNavigation { get; set; } = new List<LeaveBaseApprovalHistory>();

    public virtual ICollection<LeaveBaseApprovalHistory> LeaveBaseApprovalHistoryCreatedByNavigation { get; set; } = new List<LeaveBaseApprovalHistory>();

    public virtual ICollection<LeaveBaseApprovalHistory> LeaveBaseApprovalHistoryDeletedByNavigation { get; set; } = new List<LeaveBaseApprovalHistory>();

    public virtual ICollection<LeaveBaseApprovalHistory> LeaveBaseApprovalHistoryUpdatedByNavigation { get; set; } = new List<LeaveBaseApprovalHistory>();

    public virtual ICollection<LeavePolicyConfiguration> LeavePolicyConfigurationCreatedByNavigation { get; set; } = new List<LeavePolicyConfiguration>();

    public virtual ICollection<LeavePolicyConfiguration> LeavePolicyConfigurationDeletedByNavigation { get; set; } = new List<LeavePolicyConfiguration>();

    public virtual ICollection<LeavePolicyConfiguration> LeavePolicyConfigurationUpdatedByNavigation { get; set; } = new List<LeavePolicyConfiguration>();

    public virtual ICollection<LeaveTypes> LeaveTypesCreatedByNavigation { get; set; } = new List<LeaveTypes>();

    public virtual ICollection<LeaveTypes> LeaveTypesDeletedByNavigation { get; set; } = new List<LeaveTypes>();

    public virtual ICollection<LeaveTypes> LeaveTypesUpdatedByNavigation { get; set; } = new List<LeaveTypes>();

    public virtual ICollection<LicenceTypes> LicenceTypesCreatedByNavigation { get; set; } = new List<LicenceTypes>();

    public virtual ICollection<LicenceTypes> LicenceTypesDeletedByNavigation { get; set; } = new List<LicenceTypes>();

    public virtual ICollection<LicenceTypes> LicenceTypesUpdatedByNavigation { get; set; } = new List<LicenceTypes>();

    public virtual ICollection<Loan> LoanApprovalPerson { get; set; } = new List<Loan>();

    public virtual ICollection<LoanBaseApprovalHistory> LoanBaseApprovalHistoryApproveBy { get; set; } = new List<LoanBaseApprovalHistory>();

    public virtual ICollection<LoanBaseApprovalHistory> LoanBaseApprovalHistoryCreatedByNavigation { get; set; } = new List<LoanBaseApprovalHistory>();

    public virtual ICollection<LoanBaseApprovalHistory> LoanBaseApprovalHistoryDeletedByNavigation { get; set; } = new List<LoanBaseApprovalHistory>();

    public virtual ICollection<LoanBaseApprovalHistory> LoanBaseApprovalHistoryUpdatedByNavigation { get; set; } = new List<LoanBaseApprovalHistory>();

    public virtual ICollection<Loan> LoanCreatedByNavigation { get; set; } = new List<Loan>();

    public virtual ICollection<Loan> LoanDeletedByNavigation { get; set; } = new List<Loan>();

    public virtual ICollection<LoanDetails> LoanDetailsCreatedByNavigation { get; set; } = new List<LoanDetails>();

    public virtual ICollection<LoanDetails> LoanDetailsDeletedByNavigation { get; set; } = new List<LoanDetails>();

    public virtual ICollection<LoanDetails> LoanDetailsReceivedBy { get; set; } = new List<LoanDetails>();

    public virtual ICollection<LoanDetails> LoanDetailsUpdatedByNavigation { get; set; } = new List<LoanDetails>();

    public virtual ICollection<Loan> LoanEmployee { get; set; } = new List<Loan>();

    public virtual ICollection<LoanInstallmentPeriods> LoanInstallmentPeriodsCreatedByNavigation { get; set; } = new List<LoanInstallmentPeriods>();

    public virtual ICollection<LoanInstallmentPeriods> LoanInstallmentPeriodsDeletedByNavigation { get; set; } = new List<LoanInstallmentPeriods>();

    public virtual ICollection<LoanInstallmentPeriods> LoanInstallmentPeriodsUpdatedByNavigation { get; set; } = new List<LoanInstallmentPeriods>();

    public virtual ICollection<Loan> LoanUpdatedByNavigation { get; set; } = new List<Loan>();

    public virtual ICollection<Localizations> LocalizationsCreatedByNavigation { get; set; } = new List<Localizations>();

    public virtual ICollection<Localizations> LocalizationsDeletedByNavigation { get; set; } = new List<Localizations>();

    public virtual ICollection<Localizations> LocalizationsUpdatedByNavigation { get; set; } = new List<Localizations>();

    public virtual ICollection<Locations> LocationsCreatedByNavigation { get; set; } = new List<Locations>();

    public virtual ICollection<Locations> LocationsDeletedByNavigation { get; set; } = new List<Locations>();

    public virtual ICollection<Locations> LocationsUpdatedByNavigation { get; set; } = new List<Locations>();

    public virtual ICollection<MainAccounts> MainAccountsCreatedByNavigation { get; set; } = new List<MainAccounts>();

    public virtual ICollection<MainAccounts> MainAccountsDeletedByNavigation { get; set; } = new List<MainAccounts>();

    public virtual ICollection<MainAccounts> MainAccountsUpdatedByNavigation { get; set; } = new List<MainAccounts>();

    public virtual MaritalStatus? MaritalStatus { get; set; }

    public virtual ICollection<MaritalStatus> MaritalStatusCreatedByNavigation { get; set; } = new List<MaritalStatus>();

    public virtual ICollection<MaritalStatus> MaritalStatusUpdatedByNavigation { get; set; } = new List<MaritalStatus>();

    public virtual ICollection<MessageContent> MessageContentCreatedByNavigation { get; set; } = new List<MessageContent>();

    public virtual ICollection<MessageContent> MessageContentDeletedByNavigation { get; set; } = new List<MessageContent>();

    public virtual ICollection<MessageContent> MessageContentUpdatedByNavigation { get; set; } = new List<MessageContent>();

    public virtual ICollection<MobileApps> MobileAppsCreatedByNavigation { get; set; } = new List<MobileApps>();

    public virtual ICollection<MobileApps> MobileAppsDeletedByNavigation { get; set; } = new List<MobileApps>();

    public virtual ICollection<MobileApps> MobileAppsUpdatedByNavigation { get; set; } = new List<MobileApps>();

    public virtual Country? Nationality { get; set; }

    public virtual ICollection<OTPSettings> OTPSettingsCreatedByNavigation { get; set; } = new List<OTPSettings>();

    public virtual ICollection<OTPSettings> OTPSettingsDeletedByNavigation { get; set; } = new List<OTPSettings>();

    public virtual ICollection<OTPSettings> OTPSettingsUpdatedByNavigation { get; set; } = new List<OTPSettings>();

    public virtual ICollection<OpeningBalances> OpeningBalancesCreatedByNavigation { get; set; } = new List<OpeningBalances>();

    public virtual ICollection<OpeningBalances> OpeningBalancesDeletedByNavigation { get; set; } = new List<OpeningBalances>();

    public virtual ICollection<OpeningBalances> OpeningBalancesUpdatedByNavigation { get; set; } = new List<OpeningBalances>();

    public virtual ICollection<OrganizationBranches> OrganizationBranchesCreatedByNavigation { get; set; } = new List<OrganizationBranches>();

    public virtual ICollection<OrganizationBranches> OrganizationBranchesDeletedByNavigation { get; set; } = new List<OrganizationBranches>();

    public virtual ICollection<OrganizationBranches> OrganizationBranchesUpdatedByNavigation { get; set; } = new List<OrganizationBranches>();

    public virtual ICollection<Organization> OrganizationCreatedByNavigation { get; set; } = new List<Organization>();

    public virtual ICollection<Organization> OrganizationDeletedByNavigation { get; set; } = new List<Organization>();

    public virtual ICollection<OrganizationTypes> OrganizationTypesCreatedByNavigation { get; set; } = new List<OrganizationTypes>();

    public virtual ICollection<OrganizationTypes> OrganizationTypesDeletedByNavigation { get; set; } = new List<OrganizationTypes>();

    public virtual ICollection<OrganizationTypes> OrganizationTypesUpdatedByNavigation { get; set; } = new List<OrganizationTypes>();

    public virtual ICollection<Organization> OrganizationUpdatedByNavigation { get; set; } = new List<Organization>();

    public virtual ICollection<OtherContacts> OtherContactsCreatedByNavigation { get; set; } = new List<OtherContacts>();

    public virtual ICollection<OtherContacts> OtherContactsDeletedByNavigation { get; set; } = new List<OtherContacts>();

    public virtual ICollection<OtherContacts> OtherContactsUpdatedByNavigation { get; set; } = new List<OtherContacts>();

    public virtual ICollection<PSettings> PSettingsCreatedByNavigation { get; set; } = new List<PSettings>();

    public virtual ICollection<PSettings> PSettingsDeletedByNavigation { get; set; } = new List<PSettings>();

    public virtual ICollection<PSettings> PSettingsUpdatedByNavigation { get; set; } = new List<PSettings>();

    public virtual ICollection<PassingYears> PassingYearsCreatedByNavigation { get; set; } = new List<PassingYears>();

    public virtual ICollection<PassingYears> PassingYearsDeletedByNavigation { get; set; } = new List<PassingYears>();

    public virtual ICollection<PassingYears> PassingYearsUpdatedByNavigation { get; set; } = new List<PassingYears>();

    public virtual ICollection<PayAllowancBenifits> PayAllowancBenifitsCreatedByNavigation { get; set; } = new List<PayAllowancBenifits>();

    public virtual ICollection<PayAllowancBenifits> PayAllowancBenifitsDeletedByNavigation { get; set; } = new List<PayAllowancBenifits>();

    public virtual ICollection<PayAllowancBenifits> PayAllowancBenifitsUpdatedByNavigation { get; set; } = new List<PayAllowancBenifits>();

    public virtual ICollection<PayDeductions> PayDeductionsCreatedByNavigation { get; set; } = new List<PayDeductions>();

    public virtual ICollection<PayDeductions> PayDeductionsDeletedByNavigation { get; set; } = new List<PayDeductions>();

    public virtual ICollection<PayDeductions> PayDeductionsUpdatedByNavigation { get; set; } = new List<PayDeductions>();

    public virtual ICollection<PaySlips> PaySlipsCreatedByNavigation { get; set; } = new List<PaySlips>();

    public virtual ICollection<PaySlips> PaySlipsDeletedByNavigation { get; set; } = new List<PaySlips>();

    public virtual ICollection<PaySlips> PaySlipsEmployee { get; set; } = new List<PaySlips>();

    public virtual ICollection<PaySlips> PaySlipsUpdatedByNavigation { get; set; } = new List<PaySlips>();

    public virtual ICollection<PaymentChequeActivity> PaymentChequeActivityCreatedByNavigation { get; set; } = new List<PaymentChequeActivity>();

    public virtual ICollection<PaymentChequeActivity> PaymentChequeActivityDeletedByNavigation { get; set; } = new List<PaymentChequeActivity>();

    public virtual ICollection<PaymentChequeActivity> PaymentChequeActivityUpdatedByNavigation { get; set; } = new List<PaymentChequeActivity>();

    public virtual ICollection<PaymentChequeInfo> PaymentChequeInfoCreatedByNavigation { get; set; } = new List<PaymentChequeInfo>();

    public virtual ICollection<PaymentChequeInfo> PaymentChequeInfoDeletedByNavigation { get; set; } = new List<PaymentChequeInfo>();

    public virtual ICollection<PaymentChequeInfo> PaymentChequeInfoUpdatedByNavigation { get; set; } = new List<PaymentChequeInfo>();

    public virtual ICollection<PaymentMethods> PaymentMethodsCreatedByNavigation { get; set; } = new List<PaymentMethods>();

    public virtual ICollection<PaymentMethods> PaymentMethodsDeletedByNavigation { get; set; } = new List<PaymentMethods>();

    public virtual ICollection<PaymentMethods> PaymentMethodsUpdatedByNavigation { get; set; } = new List<PaymentMethods>();

    public virtual ICollection<PaymentModes> PaymentModesCreatedByNavigation { get; set; } = new List<PaymentModes>();

    public virtual ICollection<PaymentModes> PaymentModesDeletedByNavigation { get; set; } = new List<PaymentModes>();

    public virtual ICollection<PaymentModes> PaymentModesUpdatedByNavigation { get; set; } = new List<PaymentModes>();

    public virtual ICollection<PaymentPeriodTypes> PaymentPeriodTypesCreatedByNavigation { get; set; } = new List<PaymentPeriodTypes>();

    public virtual ICollection<PaymentPeriodTypes> PaymentPeriodTypesDeletedByNavigation { get; set; } = new List<PaymentPeriodTypes>();

    public virtual ICollection<PaymentPeriodTypes> PaymentPeriodTypesUpdatedByNavigation { get; set; } = new List<PaymentPeriodTypes>();

    public virtual ICollection<PaymentTransactions> PaymentTransactionsCreatedByNavigation { get; set; } = new List<PaymentTransactions>();

    public virtual ICollection<PaymentTransactions> PaymentTransactionsDeletedByNavigation { get; set; } = new List<PaymentTransactions>();

    public virtual ICollection<PaymentTransactions> PaymentTransactionsUpdatedByNavigation { get; set; } = new List<PaymentTransactions>();

    public virtual ICollection<Percentages> PercentagesCreatedByNavigation { get; set; } = new List<Percentages>();

    public virtual ICollection<Percentages> PercentagesDeletedByNavigation { get; set; } = new List<Percentages>();

    public virtual ICollection<Percentages> PercentagesUpdatedByNavigation { get; set; } = new List<Percentages>();

    public virtual ICollection<PostingRuleDetails> PostingRuleDetailsCreatedByNavigation { get; set; } = new List<PostingRuleDetails>();

    public virtual ICollection<PostingRuleDetails> PostingRuleDetailsDeletedByNavigation { get; set; } = new List<PostingRuleDetails>();

    public virtual ICollection<PostingRuleDetails> PostingRuleDetailsUpdatedByNavigation { get; set; } = new List<PostingRuleDetails>();

    public virtual ICollection<PostingRules> PostingRulesCreatedByNavigation { get; set; } = new List<PostingRules>();

    public virtual ICollection<PostingRules> PostingRulesDeletedByNavigation { get; set; } = new List<PostingRules>();

    public virtual ICollection<PostingRules> PostingRulesUpdatedByNavigation { get; set; } = new List<PostingRules>();

    public virtual ICollection<PriceQuotationVersionItems> PriceQuotationVersionItemsCreatedByNavigation { get; set; } = new List<PriceQuotationVersionItems>();

    public virtual ICollection<PriceQuotationVersionItems> PriceQuotationVersionItemsDeletedByNavigation { get; set; } = new List<PriceQuotationVersionItems>();

    public virtual ICollection<PriceQuotationVersionItems> PriceQuotationVersionItemsUpdatedByNavigation { get; set; } = new List<PriceQuotationVersionItems>();

    public virtual ICollection<PriceQuotationVersions> PriceQuotationVersionsCreatedByNavigation { get; set; } = new List<PriceQuotationVersions>();

    public virtual ICollection<PriceQuotationVersions> PriceQuotationVersionsDeletedByNavigation { get; set; } = new List<PriceQuotationVersions>();

    public virtual ICollection<PriceQuotationVersions> PriceQuotationVersionsUpdatedByNavigation { get; set; } = new List<PriceQuotationVersions>();

    public virtual ICollection<PriceQuotations> PriceQuotationsCreatedByNavigation { get; set; } = new List<PriceQuotations>();

    public virtual ICollection<PriceQuotations> PriceQuotationsDeletedByNavigation { get; set; } = new List<PriceQuotations>();

    public virtual ICollection<PriceQuotations> PriceQuotationsUpdatedByNavigation { get; set; } = new List<PriceQuotations>();

    public virtual ICollection<Priorities> PrioritiesCreatedByNavigation { get; set; } = new List<Priorities>();

    public virtual ICollection<Priorities> PrioritiesDeletedByNavigation { get; set; } = new List<Priorities>();

    public virtual ICollection<Priorities> PrioritiesUpdatedByNavigation { get; set; } = new List<Priorities>();

    public virtual ICollection<ProbetionPeriodSettings> ProbetionPeriodSettingsCreatedByNavigation { get; set; } = new List<ProbetionPeriodSettings>();

    public virtual ICollection<ProbetionPeriodSettings> ProbetionPeriodSettingsDeletedByNavigation { get; set; } = new List<ProbetionPeriodSettings>();

    public virtual ICollection<ProbetionPeriodSettings> ProbetionPeriodSettingsUpdatedByNavigation { get; set; } = new List<ProbetionPeriodSettings>();

    public virtual ICollection<ProductAdvancedPricing> ProductAdvancedPricingCreatedByNavigation { get; set; } = new List<ProductAdvancedPricing>();

    public virtual ICollection<ProductAdvancedPricing> ProductAdvancedPricingDeletedByNavigation { get; set; } = new List<ProductAdvancedPricing>();

    public virtual ICollection<ProductAdvancedPricing> ProductAdvancedPricingUpdatedByNavigation { get; set; } = new List<ProductAdvancedPricing>();

    public virtual ICollection<ProductAttributes> ProductAttributesCreatedByNavigation { get; set; } = new List<ProductAttributes>();

    public virtual ICollection<ProductAttributes> ProductAttributesDeletedByNavigation { get; set; } = new List<ProductAttributes>();

    public virtual ICollection<ProductAttributes> ProductAttributesUpdatedByNavigation { get; set; } = new List<ProductAttributes>();

    public virtual ICollection<ProductBarcodes> ProductBarcodesCreatedByNavigation { get; set; } = new List<ProductBarcodes>();

    public virtual ICollection<ProductBarcodes> ProductBarcodesDeletedByNavigation { get; set; } = new List<ProductBarcodes>();

    public virtual ICollection<ProductBarcodes> ProductBarcodesUpdatedByNavigation { get; set; } = new List<ProductBarcodes>();

    public virtual ICollection<ProductBrands> ProductBrandsCreatedByNavigation { get; set; } = new List<ProductBrands>();

    public virtual ICollection<ProductBrands> ProductBrandsDeletedByNavigation { get; set; } = new List<ProductBrands>();

    public virtual ICollection<ProductBrands> ProductBrandsUpdatedByNavigation { get; set; } = new List<ProductBrands>();

    public virtual ICollection<ProductCategories> ProductCategoriesCreatedByNavigation { get; set; } = new List<ProductCategories>();

    public virtual ICollection<ProductCategories> ProductCategoriesDeletedByNavigation { get; set; } = new List<ProductCategories>();

    public virtual ICollection<ProductCategories> ProductCategoriesUpdatedByNavigation { get; set; } = new List<ProductCategories>();

    public virtual ICollection<ProductImages> ProductImagesCreatedByNavigation { get; set; } = new List<ProductImages>();

    public virtual ICollection<ProductImages> ProductImagesDeletedByNavigation { get; set; } = new List<ProductImages>();

    public virtual ICollection<ProductImages> ProductImagesUpdatedByNavigation { get; set; } = new List<ProductImages>();

    public virtual ICollection<ProductPricing> ProductPricingCreatedByNavigation { get; set; } = new List<ProductPricing>();

    public virtual ICollection<ProductPricing> ProductPricingDeletedByNavigation { get; set; } = new List<ProductPricing>();

    public virtual ICollection<ProductPricing> ProductPricingUpdatedByNavigation { get; set; } = new List<ProductPricing>();

    public virtual ICollection<ProductSubCategories> ProductSubCategoriesCreatedByNavigation { get; set; } = new List<ProductSubCategories>();

    public virtual ICollection<ProductSubCategories> ProductSubCategoriesDeletedByNavigation { get; set; } = new List<ProductSubCategories>();

    public virtual ICollection<ProductSubCategories> ProductSubCategoriesUpdatedByNavigation { get; set; } = new List<ProductSubCategories>();

    public virtual ICollection<ProductTypes> ProductTypesCreatedByNavigation { get; set; } = new List<ProductTypes>();

    public virtual ICollection<ProductTypes> ProductTypesDeletedByNavigation { get; set; } = new List<ProductTypes>();

    public virtual ICollection<ProductTypes> ProductTypesUpdatedByNavigation { get; set; } = new List<ProductTypes>();

    public virtual ICollection<Products> ProductsCreatedByNavigation { get; set; } = new List<Products>();

    public virtual ICollection<Products> ProductsDeletedByNavigation { get; set; } = new List<Products>();

    public virtual ICollection<Products> ProductsUpdatedByNavigation { get; set; } = new List<Products>();

    public virtual ICollection<ProvisionPeriodTtimeTypes> ProvisionPeriodTtimeTypesCreatedByNavigation { get; set; } = new List<ProvisionPeriodTtimeTypes>();

    public virtual ICollection<ProvisionPeriodTtimeTypes> ProvisionPeriodTtimeTypesDeletedByNavigation { get; set; } = new List<ProvisionPeriodTtimeTypes>();

    public virtual ICollection<ProvisionPeriodTtimeTypes> ProvisionPeriodTtimeTypesUpdatedByNavigation { get; set; } = new List<ProvisionPeriodTtimeTypes>();

    public virtual ICollection<PurOrderBaseSAddresses> PurOrderBaseSAddressesCreatedByNavigation { get; set; } = new List<PurOrderBaseSAddresses>();

    public virtual ICollection<PurOrderBaseSAddresses> PurOrderBaseSAddressesDeletedByNavigation { get; set; } = new List<PurOrderBaseSAddresses>();

    public virtual ICollection<PurOrderBaseSAddresses> PurOrderBaseSAddressesUpdatedByNavigation { get; set; } = new List<PurOrderBaseSAddresses>();

    public virtual ICollection<PurchasOrderItemVersions> PurchasOrderItemVersionsCreatedByNavigation { get; set; } = new List<PurchasOrderItemVersions>();

    public virtual ICollection<PurchasOrderItemVersions> PurchasOrderItemVersionsDeletedByNavigation { get; set; } = new List<PurchasOrderItemVersions>();

    public virtual ICollection<PurchasOrderItemVersions> PurchasOrderItemVersionsUpdatedByNavigation { get; set; } = new List<PurchasOrderItemVersions>();

    public virtual ICollection<PurchasOrderVersions> PurchasOrderVersionsCreatedBy1 { get; set; } = new List<PurchasOrderVersions>();

    public virtual ICollection<PurchasOrderVersions> PurchasOrderVersionsCreatedByNavigation { get; set; } = new List<PurchasOrderVersions>();

    public virtual ICollection<PurchasOrderVersions> PurchasOrderVersionsDeletedByNavigation { get; set; } = new List<PurchasOrderVersions>();

    public virtual ICollection<PurchasOrderVersions> PurchasOrderVersionsUpdatedByNavigation { get; set; } = new List<PurchasOrderVersions>();

    public virtual ICollection<PurchasOrders> PurchasOrdersCreatedByNavigation { get; set; } = new List<PurchasOrders>();

    public virtual ICollection<PurchasOrders> PurchasOrdersDeletedByNavigation { get; set; } = new List<PurchasOrders>();

    public virtual ICollection<PurchasOrders> PurchasOrdersUpdatedByNavigation { get; set; } = new List<PurchasOrders>();

    public virtual ICollection<PurchaseReceiveDrafts> PurchaseReceiveDraftsCreatedByNavigation { get; set; } = new List<PurchaseReceiveDrafts>();

    public virtual ICollection<PurchaseReceiveDrafts> PurchaseReceiveDraftsDeletedByNavigation { get; set; } = new List<PurchaseReceiveDrafts>();

    public virtual ICollection<PurchaseReceiveDrafts> PurchaseReceiveDraftsUpdatedByNavigation { get; set; } = new List<PurchaseReceiveDrafts>();

    public virtual ICollection<PurchaseReceiveItemDrafts> PurchaseReceiveItemDraftsCreatedByNavigation { get; set; } = new List<PurchaseReceiveItemDrafts>();

    public virtual ICollection<PurchaseReceiveItemDrafts> PurchaseReceiveItemDraftsDeletedByNavigation { get; set; } = new List<PurchaseReceiveItemDrafts>();

    public virtual ICollection<PurchaseReceiveItemDrafts> PurchaseReceiveItemDraftsUpdatedByNavigation { get; set; } = new List<PurchaseReceiveItemDrafts>();

    public virtual ICollection<PurchaseReceiveItems> PurchaseReceiveItemsCreatedByNavigation { get; set; } = new List<PurchaseReceiveItems>();

    public virtual ICollection<PurchaseReceiveItems> PurchaseReceiveItemsDeletedByNavigation { get; set; } = new List<PurchaseReceiveItems>();

    public virtual ICollection<PurchaseReceiveItems> PurchaseReceiveItemsUpdatedByNavigation { get; set; } = new List<PurchaseReceiveItems>();

    public virtual ICollection<PurchaseReceives> PurchaseReceivesCreatedByNavigation { get; set; } = new List<PurchaseReceives>();

    public virtual ICollection<PurchaseReceives> PurchaseReceivesDeletedByNavigation { get; set; } = new List<PurchaseReceives>();

    public virtual ICollection<PurchaseReceives> PurchaseReceivesUpdatedByNavigation { get; set; } = new List<PurchaseReceives>();

    public virtual Religions? Religion { get; set; }

    public virtual ICollection<Religions> ReligionsCreatedByNavigation { get; set; } = new List<Religions>();

    public virtual ICollection<Religions> ReligionsDeletedByNavigation { get; set; } = new List<Religions>();

    public virtual ICollection<Religions> ReligionsUpdatedByNavigation { get; set; } = new List<Religions>();

    public virtual ICollection<ReportContent> ReportContentCreatedByNavigation { get; set; } = new List<ReportContent>();

    public virtual ICollection<ReportContent> ReportContentDeletedByNavigation { get; set; } = new List<ReportContent>();

    public virtual ICollection<ReportContent> ReportContentUpdatedByNavigation { get; set; } = new List<ReportContent>();


    public virtual ICollection<ReqApprovalSettings> ReqApprovalSettingsApprover { get; set; } = new List<ReqApprovalSettings>();


    public virtual ICollection<ReqApprovalSettings> ReqApprovalSettingsCreatedByNavigation { get; set; } = new List<ReqApprovalSettings>();

    public virtual ICollection<ReqApprovalSettings> ReqApprovalSettingsDeletedByNavigation { get; set; } = new List<ReqApprovalSettings>();

    public virtual ICollection<ReqApprovalSettings> ReqApprovalSettingsUpdatedByNavigation { get; set; } = new List<ReqApprovalSettings>();

    public virtual ICollection<ReqItemApprovalHistory> ReqItemApprovalHistoryApprovalPerson { get; set; } = new List<ReqItemApprovalHistory>();

    public virtual ICollection<ReqItemApprovalHistory> ReqItemApprovalHistoryCreatedByNavigation { get; set; } = new List<ReqItemApprovalHistory>();

    public virtual ICollection<ReqItemApprovalHistory> ReqItemApprovalHistoryDeletedByNavigation { get; set; } = new List<ReqItemApprovalHistory>();

    public virtual ICollection<ReqItemApprovalHistory> ReqItemApprovalHistoryUpdatedByNavigation { get; set; } = new List<ReqItemApprovalHistory>();

    public virtual ICollection<RequisitionItems> RequisitionItemsCreatedByNavigation { get; set; } = new List<RequisitionItems>();

    public virtual ICollection<RequisitionItems> RequisitionItemsDeletedByNavigation { get; set; } = new List<RequisitionItems>();

    public virtual ICollection<RequisitionItems> RequisitionItemsUpdatedByNavigation { get; set; } = new List<RequisitionItems>();

    public virtual ICollection<Requisitions> RequisitionsCreatedByNavigation { get; set; } = new List<Requisitions>();

    public virtual ICollection<Requisitions> RequisitionsDeletedByNavigation { get; set; } = new List<Requisitions>();

    public virtual ICollection<Requisitions> RequisitionsUpdatedByNavigation { get; set; } = new List<Requisitions>();

    public virtual ICollection<ResignationsApprovalHistory> ResignationsApprovalHistoryApprovalPerson { get; set; } = new List<ResignationsApprovalHistory>();

    public virtual ICollection<ResignationsApprovalHistory> ResignationsApprovalHistoryCreatedByNavigation { get; set; } = new List<ResignationsApprovalHistory>();

    public virtual ICollection<ResignationsApprovalHistory> ResignationsApprovalHistoryDeletedByNavigation { get; set; } = new List<ResignationsApprovalHistory>();

    public virtual ICollection<ResignationsApprovalHistory> ResignationsApprovalHistoryEmployee { get; set; } = new List<ResignationsApprovalHistory>();

    public virtual ICollection<ResignationsApprovalHistory> ResignationsApprovalHistoryUpdatedByNavigation { get; set; } = new List<ResignationsApprovalHistory>();

    public virtual ICollection<Resignations> ResignationsApprovalPerson { get; set; } = new List<Resignations>();

    public virtual ICollection<Resignations> ResignationsCreatedByNavigation { get; set; } = new List<Resignations>();

    public virtual ICollection<Resignations> ResignationsDeletedByNavigation { get; set; } = new List<Resignations>();

    public virtual ICollection<Resignations> ResignationsEmployee { get; set; } = new List<Resignations>();

    public virtual ICollection<Resignations> ResignationsUpdatedByNavigation { get; set; } = new List<Resignations>();

    public virtual ICollection<ResultTypes> ResultTypesCreatedByNavigation { get; set; } = new List<ResultTypes>();

    public virtual ICollection<ResultTypes> ResultTypesDeletedByNavigation { get; set; } = new List<ResultTypes>();

    public virtual ICollection<ResultTypes> ResultTypesUpdatedByNavigation { get; set; } = new List<ResultTypes>();

    public virtual ICollection<RosterInHolyDays> RosterInHolyDaysCreatedByNavigation { get; set; } = new List<RosterInHolyDays>();

    public virtual ICollection<RosterInHolyDays> RosterInHolyDaysDeletedByNavigation { get; set; } = new List<RosterInHolyDays>();

    public virtual ICollection<RosterInHolyDays> RosterInHolyDaysEmployee { get; set; } = new List<RosterInHolyDays>();

    public virtual ICollection<RosterInHolyDays> RosterInHolyDaysUpdatedByNavigation { get; set; } = new List<RosterInHolyDays>();

    public virtual ICollection<RosterInOfficeDays> RosterInOfficeDaysCreatedByNavigation { get; set; } = new List<RosterInOfficeDays>();

    public virtual ICollection<RosterInOfficeDays> RosterInOfficeDaysDeletedByNavigation { get; set; } = new List<RosterInOfficeDays>();

    public virtual ICollection<RosterInOfficeDays> RosterInOfficeDaysEmployee { get; set; } = new List<RosterInOfficeDays>();

    public virtual ICollection<RosterInOfficeDays> RosterInOfficeDaysUpdatedByNavigation { get; set; } = new List<RosterInOfficeDays>();

    public virtual ICollection<SAddressTypes> SAddressTypesCreatedByNavigation { get; set; } = new List<SAddressTypes>();

    public virtual ICollection<SAddressTypes> SAddressTypesDeletedByNavigation { get; set; } = new List<SAddressTypes>();

    public virtual ICollection<SAddressTypes> SAddressTypesUpdatedByNavigation { get; set; } = new List<SAddressTypes>();

    public virtual ICollection<SAddresses> SAddressesCreatedByNavigation { get; set; } = new List<SAddresses>();

    public virtual ICollection<SAddresses> SAddressesDeletedByNavigation { get; set; } = new List<SAddresses>();

    public virtual ICollection<SAddresses> SAddressesUpdatedByNavigation { get; set; } = new List<SAddresses>();

    public virtual ICollection<SMSSettings> SMSSettingsCreatedByNavigation { get; set; } = new List<SMSSettings>();

    public virtual ICollection<SMSSettings> SMSSettingsDeletedByNavigation { get; set; } = new List<SMSSettings>();

    public virtual ICollection<SMSSettings> SMSSettingsUpdatedByNavigation { get; set; } = new List<SMSSettings>();

    public virtual ICollection<SalaryTypes> SalaryTypesCreatedByNavigation { get; set; } = new List<SalaryTypes>();

    public virtual ICollection<SalaryTypes> SalaryTypesDeletedByNavigation { get; set; } = new List<SalaryTypes>();

    public virtual ICollection<SalaryTypes> SalaryTypesUpdatedByNavigation { get; set; } = new List<SalaryTypes>();

    public virtual ICollection<SalesOrderVersionItems> SalesOrderVersionItemsCreatedByNavigation { get; set; } = new List<SalesOrderVersionItems>();

    public virtual ICollection<SalesOrderVersionItems> SalesOrderVersionItemsDeletedByNavigation { get; set; } = new List<SalesOrderVersionItems>();

    public virtual ICollection<SalesOrderVersionItems> SalesOrderVersionItemsUpdatedByNavigation { get; set; } = new List<SalesOrderVersionItems>();

    public virtual ICollection<SalesOrders> SalesOrdersCreatedByNavigation { get; set; } = new List<SalesOrders>();

    public virtual ICollection<SalesOrders> SalesOrdersDeletedByNavigation { get; set; } = new List<SalesOrders>();

    public virtual ICollection<SalesOrders> SalesOrdersUpdatedByNavigation { get; set; } = new List<SalesOrders>();

    public virtual ICollection<SalesOrdersVersions> SalesOrdersVersionsCreatedByNavigation { get; set; } = new List<SalesOrdersVersions>();

    public virtual ICollection<SalesOrdersVersions> SalesOrdersVersionsDeletedByNavigation { get; set; } = new List<SalesOrdersVersions>();

    public virtual ICollection<SalesOrdersVersions> SalesOrdersVersionsUpdatedByNavigation { get; set; } = new List<SalesOrdersVersions>();

    public virtual ICollection<ServiceYears> ServiceYearsCreatedByNavigation { get; set; } = new List<ServiceYears>();

    public virtual ICollection<ServiceYears> ServiceYearsDeletedByNavigation { get; set; } = new List<ServiceYears>();

    public virtual ICollection<ServiceYears> ServiceYearsUpdatedByNavigation { get; set; } = new List<ServiceYears>();

    public virtual ICollection<Services> ServicesCreatedByNavigation { get; set; } = new List<Services>();

    public virtual ICollection<Services> ServicesDeletedByNavigation { get; set; } = new List<Services>();

    public virtual ICollection<Services> ServicesUpdatedByNavigation { get; set; } = new List<Services>();

    public virtual ICollection<Shifts> ShiftsCreatedByNavigation { get; set; } = new List<Shifts>();

    public virtual ICollection<Shifts> ShiftsDeletedByNavigation { get; set; } = new List<Shifts>();

    public virtual ICollection<Shifts> ShiftsUpdatedByNavigation { get; set; } = new List<Shifts>();

    public virtual ICollection<SpiralBioWeeklyPattern> SpiralBioWeeklyPatternCreatedByNavigation { get; set; } = new List<SpiralBioWeeklyPattern>();

    public virtual ICollection<SpiralBioWeeklyPattern> SpiralBioWeeklyPatternDeletedByNavigation { get; set; } = new List<SpiralBioWeeklyPattern>();

    public virtual ICollection<SpiralBioWeeklyPatternDetails> SpiralBioWeeklyPatternDetailsCreatedByNavigation { get; set; } = new List<SpiralBioWeeklyPatternDetails>();

    public virtual ICollection<SpiralBioWeeklyPatternDetails> SpiralBioWeeklyPatternDetailsDeletedByNavigation { get; set; } = new List<SpiralBioWeeklyPatternDetails>();

    public virtual ICollection<SpiralBioWeeklyPatternDetails> SpiralBioWeeklyPatternDetailsUpdatedByNavigation { get; set; } = new List<SpiralBioWeeklyPatternDetails>();

    public virtual ICollection<SpiralBioWeeklyPattern> SpiralBioWeeklyPatternUpdatedByNavigation { get; set; } = new List<SpiralBioWeeklyPattern>();

    public virtual ICollection<SpiralMonthlyPattern> SpiralMonthlyPatternCreatedByNavigation { get; set; } = new List<SpiralMonthlyPattern>();

    public virtual ICollection<SpiralMonthlyPattern> SpiralMonthlyPatternDeletedByNavigation { get; set; } = new List<SpiralMonthlyPattern>();

    public virtual ICollection<SpiralMonthlyPatternDetails> SpiralMonthlyPatternDetailsCreatedByNavigation { get; set; } = new List<SpiralMonthlyPatternDetails>();

    public virtual ICollection<SpiralMonthlyPatternDetails> SpiralMonthlyPatternDetailsDeletedByNavigation { get; set; } = new List<SpiralMonthlyPatternDetails>();

    public virtual ICollection<SpiralMonthlyPatternDetails> SpiralMonthlyPatternDetailsUpdatedByNavigation { get; set; } = new List<SpiralMonthlyPatternDetails>();

    public virtual ICollection<SpiralMonthlyPattern> SpiralMonthlyPatternUpdatedByNavigation { get; set; } = new List<SpiralMonthlyPattern>();

    public virtual ICollection<SpiralPatternAssignList> SpiralPatternAssignListCreatedByNavigation { get; set; } = new List<SpiralPatternAssignList>();

    public virtual ICollection<SpiralPatternAssignList> SpiralPatternAssignListDeletedByNavigation { get; set; } = new List<SpiralPatternAssignList>();

    public virtual ICollection<SpiralPatternAssignList> SpiralPatternAssignListEmployee { get; set; } = new List<SpiralPatternAssignList>();

    public virtual ICollection<SpiralPatternAssignList> SpiralPatternAssignListUpdatedByNavigation { get; set; } = new List<SpiralPatternAssignList>();

    public virtual ICollection<SpiralPatternTypes> SpiralPatternTypesCreatedByNavigation { get; set; } = new List<SpiralPatternTypes>();

    public virtual ICollection<SpiralPatternTypes> SpiralPatternTypesDeletedByNavigation { get; set; } = new List<SpiralPatternTypes>();

    public virtual ICollection<SpiralPatternTypes> SpiralPatternTypesUpdatedByNavigation { get; set; } = new List<SpiralPatternTypes>();

    public virtual ICollection<SpiralWeeklyPattern> SpiralWeeklyPatternCreatedByNavigation { get; set; } = new List<SpiralWeeklyPattern>();

    public virtual ICollection<SpiralWeeklyPattern> SpiralWeeklyPatternDeletedByNavigation { get; set; } = new List<SpiralWeeklyPattern>();

    public virtual ICollection<SpiralWeeklyPatternDetails> SpiralWeeklyPatternDetailsCreatedByNavigation { get; set; } = new List<SpiralWeeklyPatternDetails>();

    public virtual ICollection<SpiralWeeklyPatternDetails> SpiralWeeklyPatternDetailsDeletedByNavigation { get; set; } = new List<SpiralWeeklyPatternDetails>();

    public virtual ICollection<SpiralWeeklyPatternDetails> SpiralWeeklyPatternDetailsUpdatedByNavigation { get; set; } = new List<SpiralWeeklyPatternDetails>();

    public virtual ICollection<SpiralWeeklyPattern> SpiralWeeklyPatternUpdatedByNavigation { get; set; } = new List<SpiralWeeklyPattern>();

    public virtual ICollection<Statuses> StatusesCreatedByNavigation { get; set; } = new List<Statuses>();

    public virtual ICollection<Statuses> StatusesDeletedByNavigation { get; set; } = new List<Statuses>();

    public virtual ICollection<Statuses> StatusesUpdatedByNavigation { get; set; } = new List<Statuses>();

    public virtual ICollection<SubAccounts> SubAccountsCreatedByNavigation { get; set; } = new List<SubAccounts>();

    public virtual ICollection<SubAccounts> SubAccountsDeletedByNavigation { get; set; } = new List<SubAccounts>();

    public virtual ICollection<SubAccounts> SubAccountsUpdatedByNavigation { get; set; } = new List<SubAccounts>();

    public virtual ICollection<SupplierAddresses> SupplierAddressesCreatedByNavigation { get; set; } = new List<SupplierAddresses>();

    public virtual ICollection<SupplierAddresses> SupplierAddressesDeletedByNavigation { get; set; } = new List<SupplierAddresses>();

    public virtual ICollection<SupplierAddresses> SupplierAddressesUpdatedByNavigation { get; set; } = new List<SupplierAddresses>();

    public virtual ICollection<Suppliers> SuppliersCreatedByNavigation { get; set; } = new List<Suppliers>();

    public virtual ICollection<Suppliers> SuppliersDeletedByNavigation { get; set; } = new List<Suppliers>();

    public virtual ICollection<Suppliers> SuppliersUpdatedByNavigation { get; set; } = new List<Suppliers>();

    public virtual ICollection<TerminationApprovalHistory> TerminationApprovalHistoryApprovalPerson { get; set; } = new List<TerminationApprovalHistory>();

    public virtual ICollection<TerminationApprovalHistory> TerminationApprovalHistoryCreatedByNavigation { get; set; } = new List<TerminationApprovalHistory>();

    public virtual ICollection<TerminationApprovalHistory> TerminationApprovalHistoryDeletedByNavigation { get; set; } = new List<TerminationApprovalHistory>();

    public virtual ICollection<TerminationApprovalHistory> TerminationApprovalHistoryEmployee { get; set; } = new List<TerminationApprovalHistory>();

    public virtual ICollection<TerminationApprovalHistory> TerminationApprovalHistoryUpdatedByNavigation { get; set; } = new List<TerminationApprovalHistory>();

    public virtual ICollection<TerminationTypes> TerminationTypesCreatedByNavigation { get; set; } = new List<TerminationTypes>();

    public virtual ICollection<TerminationTypes> TerminationTypesDeletedByNavigation { get; set; } = new List<TerminationTypes>();

    public virtual ICollection<TerminationTypes> TerminationTypesUpdatedByNavigation { get; set; } = new List<TerminationTypes>();

    public virtual ICollection<Terminations> TerminationsApprovalPerson { get; set; } = new List<Terminations>();

    public virtual ICollection<Terminations> TerminationsCreatedByNavigation { get; set; } = new List<Terminations>();

    public virtual ICollection<Terminations> TerminationsDeletedByNavigation { get; set; } = new List<Terminations>();

    public virtual ICollection<Terminations> TerminationsEmployee { get; set; } = new List<Terminations>();

    public virtual ICollection<Terminations> TerminationsUpdatedByNavigation { get; set; } = new List<Terminations>();

    public virtual ICollection<TrainingYears> TrainingYearsCreatedByNavigation { get; set; } = new List<TrainingYears>();

    public virtual ICollection<TrainingYears> TrainingYearsDeletedByNavigation { get; set; } = new List<TrainingYears>();

    public virtual ICollection<TrainingYears> TrainingYearsUpdatedByNavigation { get; set; } = new List<TrainingYears>();

    public virtual ICollection<TransactionAccounts> TransactionAccountsCreatedByNavigation { get; set; } = new List<TransactionAccounts>();

    public virtual ICollection<TransactionAccounts> TransactionAccountsDeletedByNavigation { get; set; } = new List<TransactionAccounts>();

    public virtual ICollection<TransactionAccounts> TransactionAccountsUpdatedByNavigation { get; set; } = new List<TransactionAccounts>();

    public virtual ICollection<UnitTypes> UnitTypesCreatedByNavigation { get; set; } = new List<UnitTypes>();

    public virtual ICollection<UnitTypes> UnitTypesDeletedByNavigation { get; set; } = new List<UnitTypes>();

    public virtual ICollection<UnitTypes> UnitTypesUpdatedByNavigation { get; set; } = new List<UnitTypes>();

    public virtual Employees? UpdatedByNavigation { get; set; }

    public virtual ICollection<WarrantyTypes> WarrantyTypesCreatedByNavigation { get; set; } = new List<WarrantyTypes>();

    public virtual ICollection<WarrantyTypes> WarrantyTypesDeletedByNavigation { get; set; } = new List<WarrantyTypes>();

    public virtual ICollection<WarrantyTypes> WarrantyTypesUpdatedByNavigation { get; set; } = new List<WarrantyTypes>();

    public virtual ICollection<WeekendDays> WeekendDaysCreatedByNavigation { get; set; } = new List<WeekendDays>();

    public virtual ICollection<WeekendDays> WeekendDaysDeletedByNavigation { get; set; } = new List<WeekendDays>();

    public virtual ICollection<WeekendDays> WeekendDaysUpdatedByNavigation { get; set; } = new List<WeekendDays>();

    public virtual ICollection<WeekendSettings> WeekendSettingsCreatedByNavigation { get; set; } = new List<WeekendSettings>();

    public virtual ICollection<WeekendSettings> WeekendSettingsDeletedByNavigation { get; set; } = new List<WeekendSettings>();

    public virtual ICollection<WeekendSettings> WeekendSettingsUpdatedByNavigation { get; set; } = new List<WeekendSettings>();

    public virtual ICollection<Wirehouses> WirehousesCreatedByNavigation { get; set; } = new List<Wirehouses>();

    public virtual ICollection<Wirehouses> WirehousesDeletedByNavigation { get; set; } = new List<Wirehouses>();

    public virtual ICollection<Wirehouses> WirehousesUpdatedByNavigation { get; set; } = new List<Wirehouses>();

    public virtual ICollection<YearlyEndBonusTypes> YearlyEndBonusTypesCreatedByNavigation { get; set; } = new List<YearlyEndBonusTypes>();

    public virtual ICollection<YearlyEndBonusTypes> YearlyEndBonusTypesDeletedByNavigation { get; set; } = new List<YearlyEndBonusTypes>();

    public virtual ICollection<YearlyEndBonusTypes> YearlyEndBonusTypesUpdatedByNavigation { get; set; } = new List<YearlyEndBonusTypes>();
}