// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class EmployeeAdvances
{
    public int EmployeeAdvanceID { get; set; }

    public int? JobID { get; set; }

    public int? RequestedByUserID { get; set; }

    public decimal AmountRequested { get; set; }

    public DateOnly? StartDate { get; set; }

    public DateOnly? EndDate { get; set; }

    public bool? IsGroupAdvance { get; set; }

    public int? ApprovalStatusID { get; set; }

    public int? ApprovedByUserID { get; set; }

    public DateTime? ApprovalDate { get; set; }

    public string? LIP { get; set; }

    public string? LMAC { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }

    public virtual Statuses? ApprovalStatus { get; set; }

    public virtual Employees? ApprovedByUser { get; set; }

    public virtual Employees? CreatedByNavigation { get; set; }

    public virtual Employees? DeletedByNavigation { get; set; }

    public virtual Jobs? Job { get; set; }

    public virtual Employees? RequestedByUser { get; set; }

    public virtual Employees? UpdatedByNavigation { get; set; }
}