// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class Employees
{
    public int EmployeeID { get; set; }

    public string EmployeeCode { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string FatherName { get; set; }

    public string MotherName { get; set; }

    public DateOnly? DateOfBirth { get; set; }

    public string BirthCertificateNo { get; set; }

    public string BirthPlace { get; set; }

    public int? GenderID { get; set; }

    public int? BloodGroupID { get; set; }

    public int? NationalityID { get; set; }

    public string NID { get; set; }

    public int? ReligionID { get; set; }

    public int? MaritalStatusID { get; set; }

    public string CardNo { get; set; }

    public string MobileNumber { get; set; }

    public string Email { get; set; }

    public string TIN { get; set; }

    public string EmployeeImageFileName { get; set; }

    public string EmployeeSignatureFileName { get; set; }

    public string OtherActivities { get; set; }

    public string LIP { get; set; }

    public string LMAC { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }

    public virtual ICollection<ApplicationUser> AspNetUsers { get; set; } = new List<ApplicationUser>();
}