// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class EmployeeTransfer
{
    public int EmployeeTransferID { get; set; }

    public int? FromOrganizationID { get; set; }

    public int? FromOrganizationBranchID { get; set; }

    public int? ToOrganizationID { get; set; }

    public int? ToOrganizationBranchID { get; set; }

    public DateTime? TransferDate { get; set; }

    public string TransferNote { get; set; }

    public string LIP { get; set; }

    public string LMAC { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }

    public int? EmployeeID { get; set; }

    public virtual Employees CreatedByNavigation { get; set; }

    public virtual Employees DeletedByNavigation { get; set; }

    public virtual Employees Employee { get; set; }

    public virtual Organization FromOrganization { get; set; }

    public virtual OrganizationBranches FromOrganizationBranch { get; set; }

    public virtual Organization ToOrganization { get; set; }

    public virtual OrganizationBranches ToOrganizationBranch { get; set; }

    public virtual Employees UpdatedByNavigation { get; set; }
}