// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class EmployeeAllowances
{
    public int EmployeeAllowanceID { get; set; }

    public int? OrganizationID { get; set; }

    public bool? IsMobileInternetAllowanceEnabled { get; set; }

    public decimal? MobileInternetAllowance { get; set; }

    public bool? IsShiftAllowanceEnabled { get; set; }

    public decimal? ShiftAllowance { get; set; }

    public bool? IsHouseRentAllowanceEnabled { get; set; }

    public decimal? HouseRentAllowanceRate { get; set; }

    public int? HRentDependsOnSalaryTypeID { get; set; }

    public bool? IsMedicalAllowanceEnabled { get; set; }

    public decimal? MedicalAllowanceRate { get; set; }

    public int? MediAllowDepOnSalaryTypeID { get; set; }

    public bool? IsConveyanceAllowanceEnabled { get; set; }

    public decimal? ConveyanceAllowanceRate { get; set; }

    public int? ConAllowDepOnSalaryTypeID { get; set; }

    public string LIP { get; set; }

    public string LMAC { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }

    public virtual SalaryTypes ConAllowDepOnSalaryType { get; set; }

    public virtual Employees CreatedByNavigation { get; set; }

    public virtual Employees DeletedByNavigation { get; set; }

    public virtual SalaryTypes HRentDependsOnSalaryType { get; set; }

    public virtual SalaryTypes MediAllowDepOnSalaryType { get; set; }

    public virtual Organization Organization { get; set; }

    public virtual Employees UpdatedByNavigation { get; set; }
}