// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class EmployeeAdditionalInfo
{
    public int EmployeeAdditionalInfoId { get; set; }

    public int? EmployeeId { get; set; }

    public string PasportName { get; set; }

    public string PasportNo { get; set; }

    public string PasportPlaceOfIssue { get; set; }

    public DateTime? PasportIssueDate { get; set; }

    public DateTime? PasportExpireDate { get; set; }

    public string DrivingLicenceNo { get; set; }

    public int? LicenceTypeId { get; set; }

    public DateTime? DrivingLicenceIssueDate { get; set; }

    public DateTime? DrivingLicenceExpireDate { get; set; }

    public string SymbolOfVehicleClass { get; set; }

    public string DrivingLicencePlaceOfIssue { get; set; }

    public string WorkPermaitNumber { get; set; }

    public string WorkPermitType { get; set; }

    public DateTime? WorkPermitEffectiveDate { get; set; }

    public DateTime? WorkPermitExpireDate { get; set; }

    public DateTime? VisaExpireDate { get; set; }

    public string Lip { get; set; }

    public string Lmac { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }

    public virtual Employee CreatedByNavigation { get; set; }

    public virtual Employee DeletedByNavigation { get; set; }

    public virtual Employee Employee { get; set; }

    public virtual LicenceType LicenceType { get; set; }

    public virtual Employee UpdatedByNavigation { get; set; }
}