// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class EmployeeBaseBenefit
{
    public int EmployeeBaseBenefitId { get; set; }

    public int? EmployeeId { get; set; }

    public decimal? HealthInsurance { get; set; }

    public bool IsHealthInsuranceEnabled { get; set; }

    public decimal? PerformanceBonus { get; set; }

    public bool IsPerformanceBonusEnabled { get; set; }

    public int? YearlyEndBonusTypeId { get; set; }

    public bool IsYearlyEndBonusTypeIdenabled { get; set; }

    public decimal? FastivalBonusPercentage { get; set; }

    public bool IsFastivalBonusPercentageEnabled { get; set; }

    public decimal? ProvidantFundEmployeePercentage { get; set; }

    public decimal? ProvidantFundOrganizationPercentage { get; set; }

    public bool IsProvidantFundEnabled { get; set; }

    public int? ServiceYearId { get; set; }

    public string Lip { get; set; }

    public string Lmac { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }

    public virtual Employee CreatedByNavigation { get; set; }

    public virtual Employee DeletedByNavigation { get; set; }

    public virtual Employee Employee { get; set; }

    public virtual ServiceYear ServiceYear { get; set; }

    public virtual Employee UpdatedByNavigation { get; set; }

    public virtual YearlyEndBonusType YearlyEndBonusType { get; set; }
}