// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class EmployeeSalarySetting
{
    public int EmployeeSalarySettingsId { get; set; }

    public int? EmployeeId { get; set; }

    public string BankName { get; set; }

    public string BranchName { get; set; }

    public string AccountName { get; set; }

    public string AccountNo { get; set; }

    public string Address { get; set; }

    public string AtmcardNo { get; set; }

    public string RoutingNo { get; set; }

    public string Swiftcode { get; set; }

    public string Ifsccode { get; set; }

    public string BKashAccountNo { get; set; }

    public string RoketAccountNo { get; set; }

    public string NagodAccountNo { get; set; }

    public string EmployeeGid { get; set; }

    public int? GradeId { get; set; }

    public decimal? Salary { get; set; }

    public int? CurrencyId { get; set; }

    public string Lip { get; set; }

    public string Lmac { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }

    public int? PaymenPeriodTypeId { get; set; }

    public bool IsBenefitsEnabled { get; set; }

    public bool IsAllowanceEnabled { get; set; }

    public virtual Employee CreatedByNavigation { get; set; }

    public virtual Currency Currency { get; set; }

    public virtual Employee DeletedByNavigation { get; set; }

    public virtual Employee Employee { get; set; }

    public virtual Grade Grade { get; set; }

    public virtual PaymenPeriodType PaymenPeriodType { get; set; }

    public virtual Employee UpdatedByNavigation { get; set; }
}