// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class EmployeeAllowanceSetup
{
    public int EmployeeAllowanceSetupID { get; set; }

    public decimal? SalaryMin { get; set; }

    public decimal? SalaryMax { get; set; }

    public int? CalculationTypeID { get; set; }

    public decimal? Value { get; set; }

    public DateTime? EffectiveDate { get; set; }

    public string? LIP { get; set; }

    public string? LMAC { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }

    public int? EmployeeAllowanceID { get; set; }

    public virtual CalculationTypes? CalculationType { get; set; }

    public virtual Employees? CreatedByNavigation { get; set; }

    public virtual Employees? DeletedByNavigation { get; set; }

    public virtual EmployeeAllowances? EmployeeAllowance { get; set; }

    public virtual Employees? UpdatedByNavigation { get; set; }
}