// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class EmployeeAllowanceSetup
{
    public int EmployeeBenefitID { get; set; }

    public int? EmployeeAllowanceTypeID { get; set; }

    public int? OrganizationID { get; set; }

    public decimal? SalaryMin { get; set; }

    public decimal? SalaryMax { get; set; }

    public int? CalculationTypeID { get; set; }

    public decimal? Value { get; set; }

    public DateTime? EffectiveDate { get; set; }

    public bool? IsActive { get; set; }

    public string LIP { get; set; }

    public string LMAC { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }

    public virtual CalculationTypes CalculationType { get; set; }

    public virtual Employees CreatedByNavigation { get; set; }

    public virtual Employees DeletedByNavigation { get; set; }

    public virtual EmployeeAllowanceTypes EmployeeAllowanceType { get; set; }

    public virtual Organization Organization { get; set; }

    public virtual Employees UpdatedByNavigation { get; set; }
}