// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace GCTL.Data.Models
{
    public partial class GetModulesResult
    {
        public int MenuTabId { get; set; }
        public string Title { get; set; }
        public string Type { get; set; }
        public int? ParentId { get; set; }
        public int OrderBy { get; set; }
        public string ControllerName { get; set; }
        public string ViewName { get; set; }
        public string Icon { get; set; }
        public bool IsActive { get; set; }
    }
}
