// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace GCTL.Data.Models
{
    public partial class GetPaginatedEmployeeAttendanceResult
    {
        public int? EmployeeID { get; set; }
        public DateOnly AttendanceDate { get; set; }
        public string AttendanceStatus { get; set; } = default!;
    }
}
