// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using GCTL.Data.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace GCTL.Data.Models
{
    public partial interface IAppDbContextProcedures
    {
        Task<int> aaAsync(string? tableName, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<List<GetModulesResult>> GetModulesAsync(string? roleId, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<List<GetPaginatedEmployeeAttendanceResult>> GetPaginatedEmployeeAttendanceAsync(int? month, int? year, int? pageNumber, int? pageSize, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<List<GetUserByEmailResult>> GetUserByEmailAsync(string? email, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<int> Prc_GetEmployeesPagedAsync(int? pageNumber, int? pageSize, string? searchTerm, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<int> SeedDateForSCAsync(OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<List<sp_GetAllEmployeeShiftsResult>> sp_GetAllEmployeeShiftsAsync(int? pageNumber, int? pageSize, string? searchTerm, int? daysToShow, DateOnly? startDate, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<List<sp_GetUserPermissionsByRoleIdsResult>> sp_GetUserPermissionsByRoleIdsAsync(string? roleIds, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<List<sp_InsertOrUpdateShiftsResult>> sp_InsertOrUpdateShiftsAsync(DataTable? shiftInputs, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<int> sp_processFinalAttAsync(OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<List<sp_ProcessFinalDailyAttendanceResult>> sp_ProcessFinalDailyAttendanceAsync(OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<List<sp_ProcessPunchResult>> sp_ProcessPunchAsync(int? enroll_id, DateTime? cHECKTIME, string? deviceSN, string? sourceType, string? latitude, string? longitude, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
    }
}
