// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class InventoryTransfers
{
    public int InventoryTransferID { get; set; }

    public DateTime TransferDate { get; set; }

    public string LIP { get; set; }

    public string LMAC { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }

    public int? FromLocationID { get; set; }

    public int? ToLocationID { get; set; }

    public string TransferNumber { get; set; }

    public int? StatusID { get; set; }

    public int? RequestedBy { get; set; }

    public int? ApprovedBy { get; set; }

    public int? ReceivedBy { get; set; }

    public string Note { get; set; }

    public int? TotalItems { get; set; }

    public decimal? TotalQuantity { get; set; }

    public virtual Employees ApprovedByNavigation { get; set; }

    public virtual Employees CreatedByNavigation { get; set; }

    public virtual Employees DeletedByNavigation { get; set; }

    public virtual Locations FromLocation { get; set; }

    public virtual ICollection<InventoryTransferItems> InventoryTransferItems { get; set; } = new List<InventoryTransferItems>();

    public virtual Employees ReceivedByNavigation { get; set; }

    public virtual Employees RequestedByNavigation { get; set; }

    public virtual Statuses Status { get; set; }

    public virtual Locations ToLocation { get; set; }

    public virtual Employees UpdatedByNavigation { get; set; }
}