// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class InventoryTransfers
{
    public int InventoryTransferID { get; set; }

    public int? ToOrganizationID { get; set; }

    public DateTime? FromDate { get; set; }

    public DateTime? ToDate { get; set; }

    public string? LIP { get; set; }

    public string? LMAC { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }

    public int? FromLocationID { get; set; }

    public int? ToLocationID { get; set; }

    public virtual Employees? CreatedByNavigation { get; set; }

    public virtual Employees? DeletedByNavigation { get; set; }

    public virtual Locations? FromLocation { get; set; }

    public virtual Locations? ToLocation { get; set; }

    public virtual Employees? UpdatedByNavigation { get; set; }
}