// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class Invoices
{
    public int InvoiceID { get; set; }

    public string LIP { get; set; }

    public string LMAC { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }

    public bool? IsDraft { get; set; }

    public string InvoiceNumber { get; set; }

    public int? CustomerID { get; set; }

    public int? IBaseBillingAddressID { get; set; }

    public int? IBaseShippingAddressID { get; set; }

    public DateTime InvoiceDate { get; set; }

    public decimal? VatPercentage { get; set; }

    public decimal? VatAmount { get; set; }

    public decimal? SubTotal { get; set; }

    public decimal? GrandTotal { get; set; }

    public decimal? PaidAmount { get; set; }

    public string OtherReference { get; set; }

    public string InvoiceNote { get; set; }

    public int Version { get; set; }

    public bool IsFinal { get; set; }

    public decimal DueAmount { get; set; }

    public int? SalesOrderVersionID { get; set; }

    public int? InvoiceStatusID { get; set; }

    public bool IsVatAfterSubtotal { get; set; }

    public bool IsItemPriceIncludingVat { get; set; }

    public bool IsPriceWithoutVat { get; set; }

    public bool IsAit { get; set; }

    public decimal AitPercent { get; set; }

    public decimal AitAmount { get; set; }

    public bool ShowTaxColumn { get; set; }

    public decimal? GrossSubtotal { get; set; }

    public virtual ICollection<Challans> Challans { get; set; } = new List<Challans>();

    public virtual Employees CreatedByNavigation { get; set; }

    public virtual ICollection<CreditNote> CreditNote { get; set; } = new List<CreditNote>();

    public virtual Customers Customer { get; set; }

    public virtual ICollection<DebitNote> DebitNote { get; set; } = new List<DebitNote>();

    public virtual Employees DeletedByNavigation { get; set; }

    public virtual InvoiceBaseCAddresses IBaseBillingAddress { get; set; }

    public virtual InvoiceBaseCAddresses IBaseShippingAddress { get; set; }

    public virtual ICollection<InvoiceItems> InvoiceItems { get; set; } = new List<InvoiceItems>();

    public virtual Statuses InvoiceStatus { get; set; }

    public virtual ICollection<PaymentTransactions> PaymentTransactions { get; set; } = new List<PaymentTransactions>();

    public virtual SalesOrdersVersions SalesOrderVersion { get; set; }

    public virtual Employees UpdatedByNavigation { get; set; }
}