// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class InvoicesVersions
{
    public int InvoicesVersionID { get; set; }

    public string? LIP { get; set; }

    public string? LMAC { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }

    public bool? IsDraft { get; set; }

    public string? InvoiceNumber { get; set; }

    public int? CustomerID { get; set; }

    public int? IBaseBillingAddressID { get; set; }

    public int? IBaseShippingAddressID { get; set; }

    public DateTime InvoiceDate { get; set; }

    public decimal? VatPercentage { get; set; }

    public decimal? VatAmount { get; set; }

    public decimal? SubTotal { get; set; }

    public decimal? GrandTotal { get; set; }

    public decimal? PaidAmount { get; set; }

    public string? OtherReference { get; set; }

    public string? InvoiceNote { get; set; }

    public int Version { get; set; }

    public bool IsFinal { get; set; }

    public int? InvoiceID { get; set; }

    public decimal DueAmount { get; set; }

    public virtual Employees? CreatedByNavigation { get; set; }

    public virtual Customers? Customer { get; set; }

    public virtual Employees? DeletedByNavigation { get; set; }

    public virtual InvoiceBaseCAddresses? IBaseBillingAddress { get; set; }

    public virtual InvoiceBaseCAddresses? IBaseShippingAddress { get; set; }

    public virtual Invoices? Invoice { get; set; }

    public virtual ICollection<InvoiceVersionItems> InvoiceVersionItems { get; set; } = new List<InvoiceVersionItems>();

    public virtual ICollection<PaymentTransactions> PaymentTransactions { get; set; } = new List<PaymentTransactions>();

    public virtual Employees? UpdatedByNavigation { get; set; }
}