// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class Jobs
{
    public int JobID { get; set; }

    public string? JobTitle { get; set; }

    public int? JobTypeID { get; set; }

    public DateTime? StartDateTime { get; set; }

    public DateTime? EndDateTime { get; set; }

    public int? JobStatusID { get; set; }

    public string? Note { get; set; }

    public string? Location { get; set; }

    public decimal? Latitude { get; set; }

    public decimal? Longitude { get; set; }

    public string? FileLink { get; set; }

    public string? LIP { get; set; }

    public string? LMAC { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }

    public int? CustomerID { get; set; }

    public virtual Employees? CreatedByNavigation { get; set; }

    public virtual Customers? Customer { get; set; }

    public virtual Employees? DeletedByNavigation { get; set; }

    public virtual Statuses? JobStatus { get; set; }

    public virtual ICollection<JobTeams> JobTeams { get; set; } = new List<JobTeams>();

    public virtual JobTypes? JobType { get; set; }

    public virtual Employees? UpdatedByNavigation { get; set; }
}