// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class Journals
{
    public int JournalID { get; set; }

    public int? JournalTypeID { get; set; }

    public string JournalCode { get; set; }

    public int? PostingRuleID { get; set; }

    public int? FinancialYearID { get; set; }

    public string Note { get; set; }

    public DateTime? JournalDate { get; set; }

    public string FileLink { get; set; }

    public string LIP { get; set; }

    public string LMAC { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }

    public virtual Employees CreatedByNavigation { get; set; }

    public virtual Employees DeletedByNavigation { get; set; }

    public virtual FinancialYears FinancialYear { get; set; }

    public virtual ICollection<JournalDetails> JournalDetails { get; set; } = new List<JournalDetails>();

    public virtual JournalTypes JournalType { get; set; }

    public virtual PostingRules PostingRule { get; set; }

    public virtual Employees UpdatedByNavigation { get; set; }
}