// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class JournalHeadTbls
{
    public int JournalHeadTblID { get; set; }

    public string SchemaName { get; set; } = null!;

    public string TableName { get; set; } = null!;

    public string? LIP { get; set; }

    public string? LMAC { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }

    public virtual Employees? CreatedByNavigation { get; set; }

    public virtual Employees? DeletedByNavigation { get; set; }

    public virtual ICollection<JournalHeads> JournalHeads { get; set; } = new List<JournalHeads>();

    public virtual Employees? UpdatedByNavigation { get; set; }
}