// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class JournalHeads
{
    public int JournalHeadID { get; set; }

    public int? JournalHeadTblID { get; set; }

    public string LIP { get; set; }

    public string LMAC { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }

    public virtual Employees CreatedByNavigation { get; set; }

    public virtual ICollection<CreditNote> CreditNote { get; set; } = new List<CreditNote>();

    public virtual ICollection<DebitNote> DebitNote { get; set; } = new List<DebitNote>();

    public virtual Employees DeletedByNavigation { get; set; }

    public virtual JournalHeadTbls JournalHeadTbl { get; set; }

    public virtual Employees UpdatedByNavigation { get; set; }
}