// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class LeadDetailPhone
{
    public int LeadDetailPhoneID { get; set; }

    public int? LeadDetailID { get; set; }

    public int? AddressID { get; set; }

    public int? OtherContactID { get; set; }

    public string PhoneSnapshot { get; set; }

    public string LIP { get; set; }

    public string LMAC { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }

    public bool? IsOtherPhone { get; set; }

    public virtual Addresses Address { get; set; }

    public virtual Employees CreatedByNavigation { get; set; }

    public virtual Employees DeletedByNavigation { get; set; }

    public virtual LeadDetails LeadDetail { get; set; }

    public virtual OtherContacts OtherContact { get; set; }

    public virtual Employees UpdatedByNavigation { get; set; }
}