// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class LeadDetails
{
    public int LeadDetailID { get; set; }

    public int? LeadID { get; set; }

    public int? LeadActivityTypeID { get; set; }

    public DateTime? ActivityDateTime { get; set; }

    public string ActivityNote { get; set; }

    public string LIP { get; set; }

    public string LMAC { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }

    public string FileLink { get; set; }

    public string PhoneNumber { get; set; }

    public string EmailAddress { get; set; }

    public bool? IsDone { get; set; }

    public int? StatusID { get; set; }

    public virtual Employees CreatedByNavigation { get; set; }

    public virtual Employees DeletedByNavigation { get; set; }

    public virtual Leads Lead { get; set; }

    public virtual ICollection<LeadActivityComments> LeadActivityComments { get; set; } = new List<LeadActivityComments>();

    public virtual LeadActivityTypes LeadActivityType { get; set; }

    public virtual ICollection<LeadDetailEmail> LeadDetailEmail { get; set; } = new List<LeadDetailEmail>();

    public virtual ICollection<LeadDetailPhone> LeadDetailPhone { get; set; } = new List<LeadDetailPhone>();

    public virtual Statuses Status { get; set; }

    public virtual Employees UpdatedByNavigation { get; set; }
}