// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class Leads
{
    public int LeadID { get; set; }

    public bool? IsIndividualCustomer { get; set; }

    public int? LeadStatusID { get; set; }

    public int? LeadSourceID { get; set; }

    public int? LeadOwnerID { get; set; }

    public decimal? ApproximateDealValue { get; set; }

    public decimal? ProbabilityPercentage { get; set; }

    public string LeadDescription { get; set; }

    public string LIP { get; set; }

    public string LMAC { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }

    public string LeadName { get; set; }

    public int? PriorityID { get; set; }

    public bool? IsOwn { get; set; }

    public DateTime? ClosingDate { get; set; }

    public int? CustomerID { get; set; }

    public int? OrganizationID { get; set; }

    public virtual Employees CreatedByNavigation { get; set; }

    public virtual Customers Customer { get; set; }

    public virtual Employees DeletedByNavigation { get; set; }

    public virtual ICollection<LeadDetails> LeadDetails { get; set; } = new List<LeadDetails>();

    public virtual Employees LeadOwner { get; set; }

    public virtual ICollection<LeadServices> LeadServices { get; set; } = new List<LeadServices>();

    public virtual LeadSources LeadSource { get; set; }

    public virtual LeadStatuses LeadStatus { get; set; }

    public virtual ICollection<LeadTypes> LeadTypes { get; set; } = new List<LeadTypes>();

    public virtual Organization Organization { get; set; }

    public virtual Priorities Priority { get; set; }

    public virtual Employees UpdatedByNavigation { get; set; }
}