// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class LeadDetails
{
    public int LeadDetailID { get; set; }

    public int? LeadID { get; set; }

    public int? LeadActivityTypeID { get; set; }

    public DateTime? ActivityDateTime { get; set; }

    public string? ActivityNote { get; set; }

    public string? LIP { get; set; }

    public string? LMAC { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }

    public string? FileLink { get; set; }

    public string? PhoneNumber { get; set; }

    public string? EmailAddress { get; set; }

    public virtual Employees? CreatedByNavigation { get; set; }

    public virtual Employees? DeletedByNavigation { get; set; }

    public virtual Leads? Lead { get; set; }

    public virtual LeadActivityTypes? LeadActivityType { get; set; }

    public virtual Employees? UpdatedByNavigation { get; set; }
}