// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class LeaveBalances
{
    public int LeaveBalanceID { get; set; }

    public int? EmployeeID { get; set; }

    public int? LeaveTypeID { get; set; }

    public decimal? TotalLeave { get; set; }

    public decimal? Taken { get; set; }

    public int? ApplicableYear { get; set; }

    public string LIP { get; set; }

    public string LMAC { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }

    public decimal? TakenPartialHours { get; set; }

    public bool? IsFullDay { get; set; }

    public virtual Employees CreatedByNavigation { get; set; }

    public virtual Employees DeletedByNavigation { get; set; }

    public virtual Employees Employee { get; set; }

    public virtual LeaveTypes LeaveType { get; set; }

    public virtual Employees UpdatedByNavigation { get; set; }
}