// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class LeavePolicyConfiguration
{
    public int LeavePolicyConfigurationID { get; set; }

    public bool IsWeekendCountedAsLeave { get; set; }

    public bool IsHolidayCountedAsLeave { get; set; }

    public bool IsExceedLeaveBalance { get; set; }

    public string RoundOffHour { get; set; }

    public bool IsAllowRequestForPastDates { get; set; }

    public int? AllowRequestForFutureDays { get; set; }

    public int? MaximumleaveDaysPerAplication { get; set; }

    public int? MaximumGapDaysBetweenAplications { get; set; }

    public string LIP { get; set; }

    public string LMAC { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }

    public bool? IsAllowRequestForFutureDays { get; set; }

    public bool? IsMaximumleaveDaysPerAplication { get; set; }

    public bool? IsMaximumGapDaysBetweenAplications { get; set; }

    public bool IsRoundOffHour { get; set; }

    public bool IsAllowCrossLeave { get; set; }


    public DateTime? LeaveBalanceResetDate { get; set; }

    public bool EnableLeaveBalanceResetDate { get; set; }

    public virtual Employees CreatedByNavigation { get; set; }

    public virtual Employees DeletedByNavigation { get; set; }

    public virtual Employees UpdatedByNavigation { get; set; }
}