// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class LoanBaseApprovalHistory
{
    public int BaseApprovalHistoryID { get; set; }

    public int? LoanID { get; set; }

    public int? ApproveByID { get; set; }

    public int? StatusID { get; set; }

    public int? ApprovalStep { get; set; }

    public string? ApproverNote { get; set; }

    public string? LIP { get; set; }

    public string? LMAC { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }

    public virtual Employees? ApproveBy { get; set; }

    public virtual Employees? CreatedByNavigation { get; set; }

    public virtual Employees? DeletedByNavigation { get; set; }

    public virtual Loan? Loan { get; set; }

    public virtual Statuses? Status { get; set; }

    public virtual Employees? UpdatedByNavigation { get; set; }
}