// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class LoanDetails
{
    public int LoanDetailsID { get; set; }

    public int? LoanID { get; set; }

    public decimal? CurrentInstallmentAmunt { get; set; }

    public decimal? EarlyPayAmount { get; set; }

    public DateTime? PaymentDateTime { get; set; }

    public decimal? NextInstallmentAmunt { get; set; }

    public int? ReceivedByID { get; set; }

    public string LIP { get; set; }

    public string LMAC { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }

    public virtual Employees CreatedByNavigation { get; set; }

    public virtual Employees DeletedByNavigation { get; set; }

    public virtual Loan Loan { get; set; }

    public virtual Employees ReceivedBy { get; set; }

    public virtual Employees UpdatedByNavigation { get; set; }
}