// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class OpeningBalances
{
    public int OpeningBalanceID { get; set; }

    public int? TrxAccID { get; set; }

    public string? OpeningBalanceCode { get; set; }

    public decimal? Amount { get; set; }

    public string? TrxType { get; set; }

    public string? Description { get; set; }

    public string? LIP { get; set; }

    public string? LMAC { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }

    public virtual Employees? CreatedByNavigation { get; set; }

    public virtual Employees? DeletedByNavigation { get; set; }

    public virtual TransactionAccounts? TrxAcc { get; set; }

    public virtual Employees? UpdatedByNavigation { get; set; }
}