// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class OrganizationBranches
{
    public int OrganizationBranchID { get; set; }

    public int? OrganizationID { get; set; }

    public string OrganizationBranchName { get; set; }

    public string LIP { get; set; }

    public string LMAC { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }

    public string EmailAddress { get; set; }

    public string Phone { get; set; }

    public string Fax { get; set; }

    public string WebAddress { get; set; }

    public string Address { get; set; }

    public int? CountryID { get; set; }

    public string Street { get; set; }

    public string City { get; set; }

    public string PostCode { get; set; }

    public virtual ICollection<ApprovalSettings> ApprovalSettings { get; set; } = new List<ApprovalSettings>();

    public virtual ICollection<ApprovalTypes> ApprovalTypes { get; set; } = new List<ApprovalTypes>();

    public virtual Employees CreatedByNavigation { get; set; }

    public virtual Employees DeletedByNavigation { get; set; }

    public virtual ICollection<EmployeeOfficeInfo> EmployeeOfficeInfo { get; set; } = new List<EmployeeOfficeInfo>();

    public virtual Organization Organization { get; set; }

    public virtual Employees UpdatedByNavigation { get; set; }

    public virtual ICollection<WeekendSettings> WeekendSettings { get; set; } = new List<WeekendSettings>();
}