// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class OtherContacts
{
    public int OtherContactID { get; set; }

    public int? AddressID { get; set; }

    public string? FirstName { get; set; }

    public string? LastName { get; set; }

    public string? Designation { get; set; }

    public string? Phone1 { get; set; }

    public string? Phone2 { get; set; }

    public string? Email { get; set; }

    public string? LIP { get; set; }

    public string? LMAC { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }

    public virtual Addresses? Address { get; set; }

    public virtual Employees? CreatedByNavigation { get; set; }

    public virtual Employees? DeletedByNavigation { get; set; }

    public virtual Employees? UpdatedByNavigation { get; set; }
}