// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class PaymentTransactions
{
    public int PaymentTransactionID { get; set; }

    public string? TransactionRefNo { get; set; }

    public DateTime TransactionDate { get; set; }

    public int PaymentMethodID { get; set; }

    public decimal Amount { get; set; }

    public string Status { get; set; } = null!;

    public int? RelatedInvoiceID { get; set; }

    public int? BankID { get; set; }

    public int? BankBranchID { get; set; }

    public string? LIP { get; set; }

    public string? LMAC { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }

    public virtual Banks? Bank { get; set; }

    public virtual BankBranches? BankBranch { get; set; }

    public virtual ICollection<ChequeDetails> ChequeDetails { get; set; } = new List<ChequeDetails>();

    public virtual Employees? CreatedByNavigation { get; set; }

    public virtual Employees? DeletedByNavigation { get; set; }

    public virtual PaymentMethods PaymentMethod { get; set; } = null!;

    public virtual InvoicesVersions? RelatedInvoice { get; set; }

    public virtual Employees? UpdatedByNavigation { get; set; }
}