// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class PaymentChequeInfo
{
    public int PaymentChequeInfoID { get; set; }

    public string? ChequeNo { get; set; }

    public int? BankAccountInfoID { get; set; }

    public decimal Amount { get; set; }

    public DateOnly? IssueDate { get; set; }

    public DateOnly? MaturityDate { get; set; }

    public int? PurchaseReceiveID { get; set; }

    public string? LIP { get; set; }

    public string? LMAC { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }

    public int? PurchasOrderID { get; set; }

    public virtual BankAccountInfo? BankAccountInfo { get; set; }

    public virtual Employees? CreatedByNavigation { get; set; }

    public virtual Employees? DeletedByNavigation { get; set; }

    public virtual ICollection<PaymentChequeActivity> PaymentChequeActivity { get; set; } = new List<PaymentChequeActivity>();

    public virtual Employees? UpdatedByNavigation { get; set; }
}