// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class PaySlips
{
    public int PaySlipID { get; set; }

    public int? EmployeeID { get; set; }

    public DateOnly PayPeriodStart { get; set; }

    public DateOnly PayPeriodEnd { get; set; }

    public decimal BasicSalary { get; set; }

    public bool? IsPaid { get; set; }

    public string LIP { get; set; }

    public string LMAC { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }

    public virtual Employees CreatedByNavigation { get; set; }

    public virtual Employees DeletedByNavigation { get; set; }

    public virtual Employees Employee { get; set; }

    public virtual ICollection<PayAllowancBenifits> PayAllowancBenifits { get; set; } = new List<PayAllowancBenifits>();

    public virtual ICollection<PayDeductions> PayDeductions { get; set; } = new List<PayDeductions>();

    public virtual Employees UpdatedByNavigation { get; set; }
}