// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class PriceQuotations
{
    public int PriceQuotationID { get; set; }

    public string? QuotationNumber { get; set; }

    public string? LIP { get; set; }

    public string? LMAC { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }

    public virtual Employees? CreatedByNavigation { get; set; }

    public virtual Employees? DeletedByNavigation { get; set; }

    public virtual ICollection<PriceQuotationVersions> PriceQuotationVersions { get; set; } = new List<PriceQuotationVersions>();

    public virtual ICollection<SalesOrders> SalesOrders { get; set; } = new List<SalesOrders>();

    public virtual Employees? UpdatedByNavigation { get; set; }
}