// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class Products
{
    public int ProductID { get; set; }

    public int? ProductTypeID { get; set; }

    public int? ProductCategoryID { get; set; }

    public int? ProductSubCategoryID { get; set; }

    public int? ProductBrandID { get; set; }

    public string ProductName { get; set; }

    public string ProductMode { get; set; }

    public string ProductPartNo { get; set; }

    public string SKU { get; set; }

    public int? BarcodeGenerateFromID { get; set; }

    public string Barcode { get; set; }

    public decimal? Weight { get; set; }

    public int? UnitTypeID { get; set; }

    public int? AssetsTypeID { get; set; }

    public decimal? QuantityAlert { get; set; }

    public bool? IsTrackBatch { get; set; }

    public bool? IsActive { get; set; }

    public bool? IsTraceManufacturingDate { get; set; }

    public bool? IsTraceExpiryDate { get; set; }

    public bool? HasSerialNumber { get; set; }

    public string Description { get; set; }

    public string LIP { get; set; }

    public string LMAC { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }

    public bool? IsSize { get; set; }

    public bool? HasWarranty { get; set; }

    public int? WarrantyTypeID { get; set; }

    public int? WarrantyDays { get; set; }

    public decimal? ServiceHourlyRate { get; set; }

    public decimal? ServiceDailyRate { get; set; }

    public decimal? ServicePerJobRate { get; set; }

    public decimal? ServicePerMeterRate { get; set; }

    public virtual Classes AssetsType { get; set; }

    public virtual BarcodeGenerateFrom BarcodeGenerateFrom { get; set; }

    public virtual Employees CreatedByNavigation { get; set; }

    public virtual ICollection<CreditNoteItems> CreditNoteItems { get; set; } = new List<CreditNoteItems>();

    public virtual ICollection<DebitNoteItems> DebitNoteItems { get; set; } = new List<DebitNoteItems>();

    public virtual Employees DeletedByNavigation { get; set; }

    public virtual ICollection<Inventory> Inventory { get; set; } = new List<Inventory>();

    public virtual ICollection<InventoryTransactionHistory> InventoryTransactionHistory { get; set; } = new List<InventoryTransactionHistory>();

    public virtual ICollection<InventoryTransferItems> InventoryTransferItems { get; set; } = new List<InventoryTransferItems>();

    public virtual ICollection<InvoiceItems> InvoiceItems { get; set; } = new List<InvoiceItems>();

    public virtual ICollection<ProductAdvancedPricing> ProductAdvancedPricing { get; set; } = new List<ProductAdvancedPricing>();

    public virtual ICollection<ProductAttributes> ProductAttributes { get; set; } = new List<ProductAttributes>();

    public virtual ICollection<ProductBarcodes> ProductBarcodes { get; set; } = new List<ProductBarcodes>();

    public virtual ProductBrands ProductBrand { get; set; }

    public virtual ProductCategories ProductCategory { get; set; }

    public virtual ICollection<ProductImages> ProductImages { get; set; } = new List<ProductImages>();

    public virtual ICollection<ProductPricing> ProductPricing { get; set; } = new List<ProductPricing>();

    public virtual ProductSubCategories ProductSubCategory { get; set; }

    public virtual ProductTypes ProductType { get; set; }

    public virtual ICollection<PurchasOrderItemVersions> PurchasOrderItemVersions { get; set; } = new List<PurchasOrderItemVersions>();

    public virtual ICollection<PurchaseReceiveItems> PurchaseReceiveItems { get; set; } = new List<PurchaseReceiveItems>();

    public virtual ICollection<RequisitionItems> RequisitionItems { get; set; } = new List<RequisitionItems>();

    public virtual UnitTypes UnitType { get; set; }

    public virtual Employees UpdatedByNavigation { get; set; }

    public virtual WarrantyTypes WarrantyType { get; set; }
}