// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class ProductAdvancedPricing
{
    public int ProductAdvancedPriceID { get; set; }

    public int ProductID { get; set; }

    public int? CustomerGroupID { get; set; }

    public string? SpecialPriceName { get; set; }

    public int? MinQuantity { get; set; }

    public int? MaxQuantity { get; set; }

    public int? CalculationTypeID { get; set; }

    public decimal PriceValue { get; set; }

    public string? Currency { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public bool? IsActive { get; set; }

    public string? LIP { get; set; }

    public string? LMAC { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }

    public virtual CalculationTypes? CalculationType { get; set; }

    public virtual Employees? CreatedByNavigation { get; set; }

    public virtual CustomerGroup? CustomerGroup { get; set; }

    public virtual Employees? DeletedByNavigation { get; set; }

    public virtual Products Product { get; set; } = null!;

    public virtual Employees? UpdatedByNavigation { get; set; }
}