// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class PurchaseReceives
{
    public int PurchaseReceiveID { get; set; }

    public int? PurchasOrderVersionID { get; set; }

    public string PRNumber { get; set; }

    public DateTime? PRDate { get; set; }

    public string VendorBill_Chalan { get; set; }

    public DateTime? BillDate { get; set; }

    public string LIP { get; set; }

    public string LMAC { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }

    public string PRNote { get; set; }

    public int? StatusID { get; set; }

    public int? ReceivedByEmployeeID { get; set; }

    public bool? IsPartialReceive { get; set; }

    public decimal? TotalReceivedQty { get; set; }

    public decimal? TotalAcceptedQty { get; set; }

    public decimal? TotalRejectedQty { get; set; }

    public string AttachmentPath { get; set; }

    public int? LocationID { get; set; }   // new FK column
    public Locations Location { get; set; } // navigation property


    public virtual Employees CreatedByNavigation { get; set; }

    public virtual Employees DeletedByNavigation { get; set; }

    public virtual PurchasOrderVersions PurchasOrderVersion { get; set; }

    public virtual ICollection<PurchaseReceiveItemHistory> PurchaseReceiveItemHistory { get; set; } = new List<PurchaseReceiveItemHistory>();

    public virtual ICollection<PurchaseReceiveItems> PurchaseReceiveItems { get; set; } = new List<PurchaseReceiveItems>();

    public virtual Employees ReceivedByEmployee { get; set; }

    public virtual Statuses Status { get; set; }

    public virtual Employees UpdatedByNavigation { get; set; }
}