// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class PurchaseReceiveItems
{
    public int PurchaseReceiveItemID { get; set; }

    public int? PurchaseReceiveID { get; set; }

    public int? ProductID { get; set; }

    public string Note { get; set; }

    public decimal? POQuantity { get; set; }

    public decimal? ReceiveQuantity { get; set; }

    public string LIP { get; set; }

    public string LMAC { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }

    public virtual Employees CreatedByNavigation { get; set; }

    public virtual Employees DeletedByNavigation { get; set; }

    public virtual Products Product { get; set; }

    public virtual PurchaseReceives PurchaseReceive { get; set; }

    public virtual Employees UpdatedByNavigation { get; set; }
}