// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class PurchaseReceiveDrafts
{
    public int PurchaseReceiveDraftID { get; set; }

    public int? PurchasOrderID { get; set; }

    public string? PRNumber { get; set; }

    public DateTime? PRDate { get; set; }

    public string? VendorBill_Chalan { get; set; }

    public DateTime? BillDate { get; set; }

    public string? LIP { get; set; }

    public string? LMAC { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }

    public virtual Employees? CreatedByNavigation { get; set; }

    public virtual Employees? DeletedByNavigation { get; set; }

    public virtual PurchasOrders? PurchasOrder { get; set; }

    public virtual ICollection<PurchaseReceiveItemDrafts> PurchaseReceiveItemDrafts { get; set; } = new List<PurchaseReceiveItemDrafts>();

    public virtual Employees? UpdatedByNavigation { get; set; }
}