// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class PurchaseReceiveItemHistory
{
    public int PurRecItemHistoryID { get; set; }

    public int? PurchaseReceiveID { get; set; }

    public string ProductName { get; set; }

    public string BrandName { get; set; }

    public string Length { get; set; }

    public string Width { get; set; }

    public string ProductTypeName { get; set; }

    public string UnitTypeName { get; set; }

    public string Weight { get; set; }

    public string WeightUnitTypeName { get; set; }

    public string SizeUnitTypeName { get; set; }

    public string SquareFeet { get; set; }

    public string SKU { get; set; }

    public string Note { get; set; }

    public decimal? POQuantity { get; set; }

    public decimal? ReceiveQuantity { get; set; }

    public string LIP { get; set; }

    public string LMAC { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }

    public virtual Employees CreatedByNavigation { get; set; }

    public virtual Employees DeletedByNavigation { get; set; }

    public virtual PurchaseReceives PurchaseReceive { get; set; }

    public virtual Employees UpdatedByNavigation { get; set; }
}