// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class records
{
    public int id { get; set; }

    public long enroll_id { get; set; }

    public DateTime records_time { get; set; }

    public int mode { get; set; }

    public int intOut { get; set; }

    public int _event { get; set; }

    public string device_serial_num { get; set; }

    public double? temperature { get; set; }

    public string image { get; set; }

    public DateTime? records_utcTime { get; set; }
}