// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class ResultType
{
    public int ResultTypeId { get; set; }

    public string ResultTypeName { get; set; }

    public string Lip { get; set; }

    public string Lmac { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }

    public virtual Employee CreatedByNavigation { get; set; }

    public virtual Employee DeletedByNavigation { get; set; }

    public virtual ICollection<EmployeeEducationalInfo> EmployeeEducationalInfos { get; set; } = new List<EmployeeEducationalInfo>();

    public virtual Employee UpdatedByNavigation { get; set; }
}