// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class RoleModulePermissions
{
    public int Id { get; set; }

    public string? RoleId { get; set; }

    public int MenuTabId { get; set; }

    public int PermissionId { get; set; }

    public bool IsGranted { get; set; }

    public virtual MenuTab MenuTab { get; set; } = null!;

    public virtual Permissions Permission { get; set; } = null!;

    public virtual ApplicationRole? Role { get; set; }
}