// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class Rosters
{
    public int RosterID { get; set; }

    public string RosterName { get; set; }

    public int? SaturdayShiftID { get; set; }

    public int? SundayShiftID { get; set; }

    public int? MondayShiftID { get; set; }

    public int? TuesdayShiftID { get; set; }

    public int? WednesdayShiftID { get; set; }

    public int? ThursdayShiftID { get; set; }

    public int? FridayShiftID { get; set; }

    public string LIP { get; set; }

    public string LMAC { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }

    public virtual Employees CreatedByNavigation { get; set; }

    public virtual Employees DeletedByNavigation { get; set; }

    public virtual ICollection<EmployeeRosters> EmployeeRosters { get; set; } = new List<EmployeeRosters>();

    public virtual Shifts FridayShift { get; set; }

    public virtual Shifts MondayShift { get; set; }

    public virtual Shifts SaturdayShift { get; set; }

    public virtual Shifts SundayShift { get; set; }

    public virtual Shifts ThursdayShift { get; set; }

    public virtual Shifts TuesdayShift { get; set; }

    public virtual Employees UpdatedByNavigation { get; set; }

    public virtual Shifts WednesdayShift { get; set; }
}