// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class SalesOrderVersionItems
{
    public int SalesOrderVersionItemID { get; set; }

    public int? SalesOrdersVersionID { get; set; }

    public string Description { get; set; }

    public int? UnitTypeID { get; set; }

    public decimal? Area { get; set; }

    public decimal? Rate { get; set; }

    public decimal? Quantity { get; set; }

    public string LIP { get; set; }

    public string LMAC { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }

    public virtual Employees CreatedByNavigation { get; set; }

    public virtual Employees DeletedByNavigation { get; set; }

    public virtual SalesOrdersVersions SalesOrdersVersion { get; set; }

    public virtual UnitTypes UnitType { get; set; }

    public virtual Employees UpdatedByNavigation { get; set; }
}