// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class SalesOrdersVersions
{
    public int SalesOrdersVersionID { get; set; }

    public int? Version { get; set; }

    public int? CustomerID { get; set; }

    public DateTime SalesOrderDate { get; set; }

    public decimal? VatPercentage { get; set; }

    public string Note { get; set; }

    public string LIP { get; set; }

    public string LMAC { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }

    public bool? IsDraft { get; set; }

    public int? SalesOrdersID { get; set; }

    public bool IsFinal { get; set; }

    public int? LocationID { get; set; }

    // Navigation property
    public Locations Location { get; set; }


    public virtual Employees CreatedByNavigation { get; set; }

    public virtual Customers Customer { get; set; }

    public virtual Employees DeletedByNavigation { get; set; }

    public virtual ICollection<SalesOrderVersionItems> SalesOrderVersionItems { get; set; } = new List<SalesOrderVersionItems>();

    public virtual SalesOrders SalesOrders { get; set; }

    public virtual Employees UpdatedByNavigation { get; set; }
}