// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class ServiceView
{
    public int ProductID { get; set; }

    public string ProductName { get; set; } = null!;

    public int? ProductTypeID { get; set; }

    public string SKU { get; set; } = null!;

    public decimal? ServiceHourlyRate { get; set; }

    public decimal? ServiceDailyRate { get; set; }

    public decimal? ServicePerJobRate { get; set; }

    public decimal? ServicePerMeterRate { get; set; }

    public string? LIP { get; set; }

    public string? LMAC { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }
}