// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class Shifts
{
    public int ShiftID { get; set; }

    public string ShiftName { get; set; }

    public int? OrganizationID { get; set; }

    public TimeOnly? StartTime { get; set; }

    public TimeOnly? EndTime { get; set; }

    public bool IsLateCount { get; set; }

    public bool IsAutomaticORManualBreakTime { get; set; }

    public bool IsMealBreakCompulsaryOrComplementaryDeductWithShift { get; set; }

    public bool IsAllowStartAndEndTime { get; set; }

    public TimeOnly? MealBreakStartTime { get; set; }

    public TimeOnly? MealBreakEndTime { get; set; }

    public bool IsAllowOvertime { get; set; }

    public string LIP { get; set; }

    public string LMAC { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }

    public TimeOnly? GraceTime { get; set; }

    public TimeOnly? MinimumWorkingTime { get; set; }

    public TimeOnly? MinimumRequiredOvertime { get; set; }

    public TimeOnly? MaximumAllowedOvertime { get; set; }

    public TimeOnly? MealBreakTime { get; set; }

    public virtual Employees CreatedByNavigation { get; set; }

    public virtual ICollection<DefaultShifts> DefaultShifts { get; set; } = new List<DefaultShifts>();

    public virtual Employees DeletedByNavigation { get; set; }

    public virtual Organization Organization { get; set; }

    public virtual ICollection<RosterInHolyDays> RosterInHolyDays { get; set; } = new List<RosterInHolyDays>();

    public virtual ICollection<RosterInOfficeDays> RosterInOfficeDays { get; set; } = new List<RosterInOfficeDays>();

    public virtual ICollection<SpiralBioWeeklyPatternDetails> SpiralBioWeeklyPatternDetails { get; set; } = new List<SpiralBioWeeklyPatternDetails>();

    public virtual ICollection<SpiralWeeklyPatternDetails> SpiralWeeklyPatternDetails { get; set; } = new List<SpiralWeeklyPatternDetails>();

    public virtual Employees UpdatedByNavigation { get; set; }
}