// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class Shifts
{
    public int ShiftID { get; set; }

    public string? ShiftName { get; set; }

    public int? OrganizationID { get; set; }

    public TimeOnly? StartTime { get; set; }

    public TimeOnly? EndTime { get; set; }

    public bool IsLateCount { get; set; }

    public bool IsAutomaticORManualBreakTime { get; set; }

    public bool IsMealBreakCompulsaryOrComplementaryDeductWithShift { get; set; }

    public bool IsAllowStartAndEndTime { get; set; }

    public TimeOnly? MealBreakStartTime { get; set; }

    public TimeOnly? MealBreakEndTime { get; set; }

    public bool IsAllowOvertime { get; set; }

    public string? LIP { get; set; }

    public string? LMAC { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }

    public bool IsRestrictFlexibleInTime { get; set; }

    public int? InPunchCountFromMin { get; set; }

    public bool IsRestrictFlexibleOutTime { get; set; }

    public int? OutPunchCountToMin { get; set; }

    public int? GraceTime { get; set; }

    public int? MinimumWorkingTime { get; set; }

    public int? MinimumRequiredOvertime { get; set; }

    public int? MaximumAllowedOvertime { get; set; }

    public int? MealBreakTime { get; set; }

    public bool IsNextDay { get; set; }

    public virtual ICollection<Attendance> Attendance { get; set; } = new List<Attendance>();

    public virtual Employees? CreatedByNavigation { get; set; }

    public virtual ICollection<DailyAttendanceStatus> DailyAttendanceStatus { get; set; } = new List<DailyAttendanceStatus>();

    public virtual ICollection<DefaultShifts> DefaultShifts { get; set; } = new List<DefaultShifts>();

    public virtual Employees? DeletedByNavigation { get; set; }

    public virtual ICollection<EmployeeFinalShifts> EmployeeFinalShifts { get; set; } = new List<EmployeeFinalShifts>();

    public virtual Organization? Organization { get; set; }

    public virtual ICollection<RosterInHolyDays> RosterInHolyDays { get; set; } = new List<RosterInHolyDays>();

    public virtual ICollection<RosterInOfficeDays> RosterInOfficeDays { get; set; } = new List<RosterInOfficeDays>();

    public virtual ICollection<SpiralBioWeeklyPatternDetails> SpiralBioWeeklyPatternDetails { get; set; } = new List<SpiralBioWeeklyPatternDetails>();

    public virtual ICollection<SpiralMonthlyPatternDetails> SpiralMonthlyPatternDetails { get; set; } = new List<SpiralMonthlyPatternDetails>();

    public virtual ICollection<SpiralWeeklyPatternDetails> SpiralWeeklyPatternDetails { get; set; } = new List<SpiralWeeklyPatternDetails>();

    public virtual Employees? UpdatedByNavigation { get; set; }
}