// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class ShipmentItems
{
    public int ShipmentItemID { get; set; }

    public int? ShipmentID { get; set; }

    public int? ProductID { get; set; }

    public decimal? OrderedQuantity { get; set; }

    public decimal? ShippedQuantity { get; set; }

    public int? FromLocationID { get; set; }

    public string Note { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }

    public virtual Employees CreatedByNavigation { get; set; }

    public virtual Employees DeletedByNavigation { get; set; }

    public virtual Locations FromLocation { get; set; }

    public virtual Products Product { get; set; }

    public virtual Shipments Shipment { get; set; }

    public virtual Employees UpdatedByNavigation { get; set; }
}