// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class ShippingMethods
{
    public int ShippingMethodID { get; set; }

    public string MethodName { get; set; }

    public string Description { get; set; }

    public decimal? BaseCost { get; set; }

    public bool? IsActive { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }

    public virtual Employees CreatedByNavigation { get; set; }

    public virtual Employees DeletedByNavigation { get; set; }

    public virtual ICollection<Shipments> Shipments { get; set; } = new List<Shipments>();

    public virtual Employees UpdatedByNavigation { get; set; }
}