// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class Shipments
{
    public int ShipmentID { get; set; }

    public string ShipmentNumber { get; set; }

    public int? InvoiceID { get; set; }

    public DateTime? ShipmentDate { get; set; }

    public DateTime? ExpectedDeliveryDate { get; set; }

    public DateTime? ActualDeliveryDate { get; set; }

    public int? StatusID { get; set; }

    public int? ShippingMethodID { get; set; }

    public string TrackingNumber { get; set; }

    public int? ShippingAddressID { get; set; }

    public string Note { get; set; }

    public decimal? ShippingCost { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }

    public int? SalesOrdersVersionID { get; set; }

    public virtual Employees CreatedByNavigation { get; set; }

    public virtual Employees DeletedByNavigation { get; set; }

    public virtual Invoices Invoice { get; set; }

    public virtual SalesOrdersVersions SalesOrdersVersion { get; set; }

    public virtual ICollection<ShipmentItems> ShipmentItems { get; set; } = new List<ShipmentItems>();

    public virtual InvoiceBaseCAddresses ShippingAddress { get; set; }

    public virtual ShippingMethods ShippingMethod { get; set; }

    public virtual Statuses Status { get; set; }

    public virtual Employees UpdatedByNavigation { get; set; }
}