// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace GCTL.Data.Models
{
    public partial class sp_GetAllEmployeeShiftsResult
    {
        public int EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public int OrganizationID { get; set; }
        public int OrganizationBranchID { get; set; }
        public string OrganizationBranchName { get; set; }
        public string OrganizationName { get; set; }
        public int DepartmentID { get; set; }
        public string DepartmentName { get; set; }
        public int ShiftID { get; set; }
        public string ShiftName { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public string WeekdayNumbers { get; set; }
        public DateOnly? FromDate { get; set; }
        public DateOnly? ToDate { get; set; }
    }
}
