// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
// <<<<<<< Debanjan
// using System.ComponentModel.DataAnnotations;
// =======
// >>>>>>> dev
using System.ComponentModel.DataAnnotations.Schema;

namespace GCTL.Data.Models
{
    public partial class sp_GetAllEmployeeShiftsResult
    {
        public int? EmployeeID { get; set; }
// <<<<<<< Debanjan
        [StringLength(154)]
        public string EmployeeName { get; set; }
        public int? OrganizationID { get; set; }
        public int? OrganizationBranchID { get; set; }
        [StringLength(50)]
        public string OrganizationBranchName { get; set; }
        [StringLength(50)]
        public string OrganizationName { get; set; }
        public int? DepartmentID { get; set; }
        [StringLength(50)]
        public string DepartmentName { get; set; }
        public int? ShiftID { get; set; }
        [StringLength(20)]
        public string ShiftName { get; set; }
        [StringLength(5)]
        public string StartTime { get; set; }
        [StringLength(5)]
        public string EndTime { get; set; }
        [StringLength(8000)]
// =======
//         public string EmployeeName { get; set; }
//         public int? OrganizationID { get; set; }
//         public int? OrganizationBranchID { get; set; }
//         public string OrganizationBranchName { get; set; }
//         public string OrganizationName { get; set; }
//         public int? DepartmentID { get; set; }
//         public string DepartmentName { get; set; }
//         public int? ShiftID { get; set; }
//         public string ShiftName { get; set; }
//         public string StartTime { get; set; }
//         public string EndTime { get; set; }
// >>>>>>> dev
        public string WeekdayNumbers { get; set; }
        public DateOnly? FromDate { get; set; }
        public DateOnly? ToDate { get; set; }
    }
}
