// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace GCTL.Data.Models
{
    public partial class sp_GetUserPermissionsByRoleIdsResult
    {
        public int Id { get; set; }
        [StringLength(450)]
        public string RoleId { get; set; }
        public int MenuTabId { get; set; }
        public int PermissionId { get; set; }
        public bool IsGranted { get; set; }
        [StringLength(100)]
        public string MenuTabTitle { get; set; }
        [StringLength(2147483647)]
        public string PermissionName { get; set; }
    }
}
