// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace GCTL.Data.Models
{
    public partial class sp_GetUserPermissionsByRoleIdsResult
    {
        public int Id { get; set; }
        public string? RoleId { get; set; }
        public int MenuTabId { get; set; }
        public int PermissionId { get; set; }
        public bool IsGranted { get; set; }
        public string MenuTabTitle { get; set; } = default!;
        public string? PermissionName { get; set; }
    }
}
