// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class SubAccounts
{
    public int SubAccountID { get; set; }

    public int MainAccountID { get; set; }

    public string SubAccountCode { get; set; }

    public string SubAccountName { get; set; }

    public string Description { get; set; }

    public string LIP { get; set; }

    public string LMAC { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }

    public virtual Employees CreatedByNavigation { get; set; }

    public virtual Employees DeletedByNavigation { get; set; }

    public virtual MainAccounts MainAccount { get; set; }

    public virtual ICollection<PostingRuleDetails> PostingRuleDetails { get; set; } = new List<PostingRuleDetails>();

    public virtual ICollection<TransactionAccounts> TransactionAccounts { get; set; } = new List<TransactionAccounts>();

    public virtual Employees UpdatedByNavigation { get; set; }
}