// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class TenantInfo
{
    public int Id { get; set; }

    public string TenantName { get; set; }

    public string Identifier { get; set; }

    public string ConnectionString { get; set; }

    public string Description { get; set; }

    //public virtual ICollection<AspNetRoles> AspNetRoles { get; set; } = new List<AspNetRoles>();

    //public virtual ICollection<AspNetUsers> AspNetUsers { get; set; } = new List<AspNetUsers>();

    public virtual ICollection<Organization> Organization { get; set; } = new List<Organization>(); 
    public ICollection<ApplicationUser> AspNetUsers { get; set; } = new List<ApplicationUser>();
    public ICollection<ApplicationRole> AspNetRoles { get; set; } = new List<ApplicationRole>();
}

