// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class Timezones
{
    public int TimezoneID { get; set; }

    public string TimezoneName { get; set; } = null!;

    public string TimezoneValue { get; set; } = null!;

    public virtual ICollection<Localizations> Localizations { get; set; } = new List<Localizations>();
}