// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class TransactionAccounts
{
    public int TrxAccID { get; set; }

    public int SubAccountID { get; set; }

    public string TrxAccCode { get; set; } = null!;

    public string TrxAccName { get; set; } = null!;

    public bool IsActive { get; set; }

    public string? Description { get; set; }

    public string? LIP { get; set; }

    public string? LMAC { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }

    public int? HeadID { get; set; }

    public virtual Employees? CreatedByNavigation { get; set; }

    public virtual Employees? DeletedByNavigation { get; set; }

    public virtual Heads? Head { get; set; }

    public virtual ICollection<JournalDetails> JournalDetails { get; set; } = new List<JournalDetails>();

    public virtual ICollection<OpeningBalances> OpeningBalances { get; set; } = new List<OpeningBalances>();

    public virtual ICollection<PostingRuleDetails> PostingRuleDetails { get; set; } = new List<PostingRuleDetails>();

    public virtual SubAccounts SubAccount { get; set; } = null!;

    public virtual Employees? UpdatedByNavigation { get; set; }
}