// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class WeekendSettings
{
    public int WeekendSettingID { get; set; }

    public int? OrganizationID { get; set; }

    public int? OrganizationBranchID { get; set; }

    public string? LIP { get; set; }

    public string? LMAC { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }

    public virtual Employees? CreatedByNavigation { get; set; }

    public virtual Employees? DeletedByNavigation { get; set; }

    public virtual Organization? Organization { get; set; }

    public virtual OrganizationBranches? OrganizationBranch { get; set; }

    public virtual Employees? UpdatedByNavigation { get; set; }

    public virtual ICollection<WeekendDays> WeekendDays { get; set; } = new List<WeekendDays>();
}